const guide=(title,summary,inputs,output,code)=>({title,summary,useWhen:summary,inputs:Object.fromEntries(inputs.map(x=>[x,"Required input."])),output,code,tryThis:"Change an input, keep maxWork sufficient, and draw the detached result.",pitfalls:["Inputs are strict plain data and outputs do not retain them."]});
export const materialsAApiGuides={
"raster.floyd-steinberg-dither":guide("Diffuse monochrome error","Make directional binary texture.",["values","columns","rows","threshold","maxWork"],"{bits}",`const result = floydSteinbergDither({ values:[.4,.6], columns:2, rows:1, threshold:.5, maxWork:3 });\nconsole.log(result);`),
"raster.bayer-dither":guide("Screen a field","Use a periodic ordered threshold.",["values","columns","rows","order","maxWork"],"{bits}",`const result = bayerDither({ values:[.5], columns:1, rows:1, order:1, maxWork:1 });\nconsole.log(result);`),
"raster.convolve-2d-signed":guide("Convolve signed values","Apply a reversed kernel to a scalar raster.",["values","columns","rows","kernel","kernelColumns","kernelRows","boundary","maxWork"],"{values}",`const result = convolve2DSigned({ values:[2], columns:1, rows:1, kernel:[3], kernelColumns:1, kernelRows:1, boundary:"zero", maxWork:1 });\nconsole.log(result);`),
"raster.binary-morphology-2d":guide("Grow or shrink a mask","Apply an active binary element.",["mask","columns","rows","element","elementColumns","elementRows","mode","boundary","maxWork"],"{mask}",`const result = binaryMorphology2D({ mask:[true], columns:1, rows:1, element:[true], elementColumns:1, elementRows:1, mode:"dilate", boundary:"zero", maxWork:1 });\nconsole.log(result);`),
"field.euclidean-distance-transform-2d":guide("Measure feature distance","Find nearest mask feature per cell.",["mask","columns","rows","maxWork"],"{distances,nearestIndices}",`const result = euclideanDistanceTransform2D({ mask:[true,false], columns:2, rows:1, maxWork:12 });\nconsole.log(result);`),
"color.oklab-ramp":guide("Interpolate perceptual stops","Build a clipped encoded-sRGB ramp.",["stops","count","maxWork"],"{colors}",`const result = oklabRamp({ stops:[[1,0,0],[0,0,1]], count:3, maxWork:5 });\nconsole.log(result);`),
"color.median-cut-quantize":guide("Reduce RGB colors","Split source colors into stable median-cut boxes.",["colors","count","maxWork"],"{palette,indices}",`const result = medianCutQuantize({ colors:[[0,0,0],[1,1,1]], count:2, maxWork:14 });\nconsole.log(result);`)};
