const meanings={vectors:"Row-major [vx,vy] samples.",columns:"Grid column count.",rows:"Grid row count or generated row count.",origin:"Lower-left grid coordinate.",spacing:"Positive physical [x,y] grid spacing.",start:"Initial trace coordinate.",dt:"Nonnegative integration timestep.",steps:"Requested fixed RK4 steps.",boundary:"Named edge behavior.",maxWork:"Explicit bounded-work allowance.",state:"Old {u,v} signed concentration arrays.",diffusionU:"U diffusion coefficient.",diffusionV:"V diffusion coefficient.",feed:"U feed coefficient.",kill:"V removal coefficient.",cells:"Old row-major 0/1 cells.",birth:"Strictly increasing neighbor counts that create cells.",survival:"Strictly increasing neighbor counts that preserve cells.",initial:"First 0/1 elementary row.",rule:"Integer Wolfram rule from 0 through 255.",values:"Row-major scalar samples."};
const guide=(title,summary,inputs,output,code)=>({title,summary,useWhen:summary,inputs:Object.fromEntries(inputs.map(x=>[x,meanings[x]??"Required finite input."])),output,code,tryThis:"Change an explicit field and render the detached result.",pitfalls:["Supply finite values and the required maxWork budget."]});
export const systemsAApiGuides={
 "path.rk4-vector-grid-trace-2d":guide("Trace a vector grid","Fourth-order trace through supplied velocities.",["vectors","columns","rows","origin","spacing","start","dt","steps","boundary","maxWork"],"{points,completedSteps,termination}.",`const result = rk4VectorGridTrace2D({ vectors:[[1,0],[1,0],[1,0],[1,0]], columns:2, rows:2, origin:[0,0], spacing:[1,1], start:[.2,.5], dt:.2, steps:3, boundary:"STOP", maxWork:56 });
console.log(result);`),
 "field.gray-scott-step-2d":guide("Advance Gray-Scott chemistry","One synchronous reaction/diffusion update.",["state","columns","rows","spacing","diffusionU","diffusionV","feed","kill","dt","boundary","maxWork"],"{u,v} next signed scalar grids.",`const result = grayScottStep2D({ state:{u:[1],v:[0]}, columns:1, rows:1, spacing:[1,1], diffusionU:0, diffusionV:0, feed:.03, kill:.06, dt:1, boundary:"CLAMP", maxWork:9 });
console.log(result);`),
 "field.life-like-step-2d":guide("Advance binary cells","One simultaneous totalistic cellular update.",["cells","columns","rows","birth","survival","boundary","maxWork"],"{cells} next binary row-major grid.",`const result = lifeLikeStep2D({ cells:[0,1,0,0,1,0,0,1,0], columns:3, rows:3, birth:[3], survival:[2,3], boundary:"DEAD", maxWork:81 });
console.log(result);`),
 "field.elementary-cellular-rows":guide("Generate rule rows","Build a bounded space-time elementary automaton.",["initial","rule","rows","boundary","maxWork"],"{columns,rows,cells} row-major output.",`const result = elementaryCellularRows({ initial:[0,0,1,0,0], rule:90, rows:4, boundary:"ZERO", maxWork:65 });
console.log(result);`),
 "field.scalar-grid-curl-2d":guide("Rotate a scalar gradient","Make tangent vectors from finite differences.",["values","columns","rows","spacing","boundary","maxWork"],"{vectors} row-major [x,y] curl vectors.",`const result = scalarGridCurl2D({ values:[0,1,0,1], columns:2, rows:2, spacing:[1,1], boundary:"ONE_SIDED", maxWork:20 });
console.log(result);`),
};
