import type { ControlGroup, Layer } from "../types.js";
import { choice, numeric, toggle, type StudioDefinition } from "./types.js";
import { pathsASettings, drawRoundedPanels, drawFlowingBrushes, drawContourAbstraction, drawGestureSkeletons, drawRoadMargins, drawNestedContourStrokes, drawFacetedSilhouettes, drawConcaveGrain } from "@procedurals/javascript/examples/paths-a-studies.js"
import { drawPathsAQuality, validatePathsAQuality } from "./paths-a-quality.js";
import { drawPathGestures, validatePathGestures } from "./paths-a-gestures.js";

const specs: [string, string, string, [string, string, number, number, number?], [string, string, number, number, number?]][] = [
  ["rounded-panels", "Rounded panels", "Corner-cut quilt panels.", ["iterations", "Refinement", 1, 5], ["panels", "Panels", 2, 9]],
  ["flowing-brushes", "Flowing brushes", "Refined calligraphic ribbons.", ["iterations", "Refinement", 1, 5], ["rows", "Rows", 3, 16]],
  ["contour-abstraction", "Contour abstraction", "One path at several simplification levels.", ["tolerance", "Tolerance", 1, 40], ["layers", "Layers", 3, 10]],
  ["gesture-skeletons", "Gesture skeletons", "Retained joints from loose drawn gestures.", ["tolerance", "Tolerance", 1, 24], ["gestures", "Gestures", 3, 14]],
  ["road-margins", "Road margins", "Parallel offset route edges.", ["distance", "Margin", 2, 30], ["routes", "Routes", 2, 8]],
  ["nested-contour-strokes", "Nested contour strokes", "Offset rings from one boundary.", ["distance", "Ring gap", 2, 18], ["rings", "Rings", 3, 12]],
  ["faceted-silhouettes", "Faceted silhouettes", "Triangulated convex paper-cut forms.", ["scale", "Scale", 120, 270], ["grain", "Grain lines", 0, 36]],
  ["concave-grain", "Concave grain", "Triangulated notched grain silhouette.", ["scale", "Scale", 120, 280], ["grain", "Grain lines", 0, 70]],
];
const n = (key: string, label: string, description: string, min: number, max: number, hardMin: number, hardMax: number, step = 1, integer = false) =>
  numeric(key, label, description, min, max, step, { hardMin, hardMax, integer });

const sourceShape = [
  n("sides", "Sides", "Number of sides in the source polygon.", 3, 12, 3, 256, 1, true),
  n("notch", "Notch depth", "Pulls one edge inward before the path operation.", 0, .9, 0, .95, .01),
  n("aspect", "Height ratio", "Stretches the source outline vertically.", .3, 2, .01, 100, .01),
  n("rotation", "Rotation", "Turns the source outline in degrees.", -180, 180, -1_000_000, 1_000_000, 1),
];
const weight = n("weight", "Stroke weight", "Width of outlines and line marks in pixels.", 0, 12, 0, 100, .25);
const trajectory = [
  n("sourceSpan", "Path span", "Length of the sampled source along its direction; zero folds all travel into a local mark.", 60, 600, 0, 10000),
  n("amplitude", "Bend amplitude", "Signed reach across the path direction.", -120, 120, -10000, 10000),
  n("forwardBend", "Forward bend", "Bend along the travel direction as well as across it; strong values produce folds and loops.", -180, 180, -10000, 10000),
  n("frequency", "Bend cycles", "Oscillations along the source; zero draws a straight path.", -4, 4, -1000, 1000, .05),
  n("disorder", "Noise blend", "Mixes a coherent seeded noise field into the analytic wave.", 0, 1, 0, 1, .01),
  n("sourcePoints", "Source points", "Samples in each trajectory before smoothing or simplification.", 6, 90, 2, 1000, 1, true),
  n("direction", "Direction", "Direction of travel in degrees; spacing follows its normal.", -180, 180, -1_000_000, 1_000_000),
  n("sourceCenterX", "Center X", "Horizontal center of the path group on the 640-pixel canvas.", 0, 640, -10000, 10000),
  n("sourceCenterY", "Center Y", "Vertical center of the path group on the 640-pixel canvas.", 0, 640, -10000, 10000),
  n("spacing", "Path spacing", "Signed separation of source paths along the direction's normal; zero overlaps.", -140, 140, -10000, 10000),
  n("variation", "Placement variation", "Maximum independent seeded shift per path in either axis; on brushes also varies wave phase.", 0, 100, 0, 10000),
];
const nodeControls = [
  toggle("showNodes", "Show nodes", "Draw source points on brushes, retained simplified joints on other studies."),
  n("nodeSize", "Node size", "Diameter of optional point marks, independent of line weight.", 0, 12, 0, 1000, .25),
];
/** Source outline shared by the polygon studies. */
const outlineShape: ControlGroup = { label: "Shape", controls: ["sides", "notch", "aspect", "rotation"] };
/** Sampled-trajectory studies share their path setup; `processing` is the study's own refinement or simplification. */
const trajectoryGroups = (count: string, processing: ControlGroup): ControlGroup[] => [
  { label: "Paths", stage: "form", controls: [count, "spacing", "variation", "sourcePoints"] },
  { label: "Placement", stage: "frame", controls: ["sourceCenterX", "sourceCenterY", "sourceSpan", "direction"] },
  { label: "Bend", stage: "process", controls: ["frequency", "amplitude", "forwardBend", "disorder"] },
  processing,
  { label: "Drawing", stage: "material", controls: ["weight", { label: "Nodes", controls: ["showNodes", "nodeSize"] }] },
];
const modern: Record<string, StudioDefinition> = {
  "rounded-panels": {
    id: "rounded-panels", title: "Rounded panels", description: "Repeat editable polygon outlines after Chaikin corner cuts.",
    procedure: "Arrange straight-sided polygon panels in staggered rows and columns, each built as an editable outline that can be stretched, rotated or notched. Round every outline with Chaikin corner cuts, then draw it filled, outlined or both.",
    parameters: [
      n("iterations", "Corner cuts", "Successive smoothing passes on each source outline.", 0, 6, 0, 16, 1, true),
      n("panels", "Panels", "Total repeated panels.", 1, 16, 1, 1000, 1, true), weight,
      ...sourceShape,
      n("panelSize", "Panel radius", "Size of each source outline before smoothing.", 20, 130, .01, 10000),
      n("columns", "Columns", "Number of panels on each row.", 1, 8, 1, 1000, 1, true),
      n("gapX", "Column gap", "Space between panel bounds; negative values overlap.", -120, 180, -10000, 10000),
      n("gapY", "Row gap", "Space between panel bounds; negative values overlap.", -120, 180, -10000, 10000),
      n("stagger", "Row stagger", "Horizontal row shift as a fraction of column pitch.", -1, 1, -100, 100, .01),
      choice("treatment", "Treatment", "Outline, filled panel, or both.", ["outline", "fill", "both"]),
      n("fillAlpha", "Fill opacity", "Opacity of the bounded panel fill.", 0, 255, 0, 255, 1, true),
    ],
    controlGroups: [
      { label: "Layout", stage: "form", controls: ["panels", "columns", { label: "Spacing", controls: ["gapX", "gapY"] }, "stagger"] },
      { label: "Panel", stage: "form", controls: ["panelSize", outlineShape, "iterations"] },
      { label: "Drawing", stage: "material", controls: ["treatment", "weight", "fillAlpha"] },
    ],
    defaults: {iterations: 2,
      panels: 6,
      weight: 2,
      sides: 5,
      notch: .25,
      aspect: 1,
      rotation: -18,
      panelSize: 57,
      columns: 3,
      gapX: 26,
      gapY: 34,
      stagger: .2,
      treatment: "both",
      fillAlpha: 95},
    validate: params => validatePathsAQuality("rounded-panels", params),
  },
  "flowing-brushes": {
    id: "flowing-brushes", title: "Flowing brushes", description: "Smooth continuous sweeps from replaceable sampled source trajectories.",
    procedure: "Sample several wavy, slightly noisy trajectories as angular polylines, then round each with passes of Chaikin corner cutting. Space the smoothed paths across their direction of travel and draw each as one continuous stroke on a transparent ground.",
    parameters: [
      n("iterations", "Corner cuts", "Chaikin refinement passes on every sampled source path.", 0, 5, 0, 16, 1, true),
      n("rows", "Brush paths", "Number of sweeps across the group's spacing.", 1, 12, 1, 1000, 1, true), weight,
      ...trajectory, ...nodeControls,
    ],
    controlGroups: trajectoryGroups("rows", { label: "Smoothing", stage: "process", controls: ["iterations"] }),
    defaults: {iterations: 3,
      rows: 5,
      weight: 3,
      sourceSpan: 440,
      amplitude: 48,
      forwardBend: 90,
      frequency: 1.4,
      disorder: .25,
      sourcePoints: 18,
      direction: -15,
      sourceCenterX: 320,
      sourceCenterY: 320,
      spacing: 52,
      variation: 12,
      showNodes: false,
      nodeSize: 5},
    validate: params => validatePathGestures("flowing-brushes", params),
  },
  "contour-abstraction": {
    id: "contour-abstraction", title: "Contour abstraction",
    description: "Layer coarse-to-fine simplified records of one sampled trajectory.",
    procedure: "Sample one bending trajectory, then simplify it repeatedly with a falling tolerance, coarsest first. Offset each simplified record across the direction of travel and draw it as an open line, so the stack moves from a few large turns to fine detail.",
    parameters: [
      n("tolerance", "Coarsest tolerance", "Simplification tolerance of the first record; later records retain increasingly fine detail.", 0, 100, 0, 10000),
      n("layers", "Records", "Number of simplified records of the source.", 1, 12, 1, 1000, 1, true), weight,
      ...trajectory, ...nodeControls,
    ],
    controlGroups: trajectoryGroups("layers", { label: "Simplification", stage: "process", controls: ["tolerance"] }),
    defaults: {tolerance: 27,
      layers: 5,
      weight: 2,
      sourceSpan: 450,
      amplitude: 87,
      forwardBend: 60,
      frequency: 1.7,
      disorder: .4,
      sourcePoints: 72,
      direction: -12,
      sourceCenterX: 320,
      sourceCenterY: 320,
      spacing: 34,
      variation: 0,
      showNodes: false,
      nodeSize: 4},
    validate: params => validatePathGestures("contour-abstraction", params),
  },
  "gesture-skeletons": {
    id: "gesture-skeletons", title: "Gesture skeletons",
    description: "Sparse articulated fragments from independently seeded sampled gestures.",
    procedure: "Generate several independently seeded open gestures as sampled curves, then simplify each polyline, dropping every bend smaller than the joint tolerance. Draw the surviving joints joined by straight segments, leaving sparse articulated fragments.",
    parameters: [
      n("tolerance", "Joint tolerance", "Simplification distance controlling which gesture joints survive.", 0, 65, 0, 10000),
      n("gestures", "Gestures", "Number of independently seeded gestures.", 1, 14, 1, 1000, 1, true), weight,
      ...trajectory, ...nodeControls,
    ],
    controlGroups: trajectoryGroups("gestures", { label: "Simplification", stage: "process", controls: ["tolerance"] }),
    defaults: {tolerance: 13,
      gestures: 6,
      weight: 2.5,
      sourceSpan: 180,
      amplitude: 32,
      forwardBend: 80,
      frequency: 1.35,
      disorder: .4,
      sourcePoints: 28,
      direction: -32,
      sourceCenterX: 320,
      sourceCenterY: 320,
      spacing: 55,
      variation: 20,
      showNodes: false,
      nodeSize: 5},
    validate: params => validatePathGestures("gesture-skeletons", params),
  },
  "road-margins": {
    id: "road-margins", title: "Road margins", description: "Offset editable open routes with optional centerlines and source nodes.",
    procedure: "Generate winding open routes from sinusoidally bent waypoints, smooth each with Chaikin corner cuts and offset it to the left and right by a signed margin. Draw the offset edges as lines, with the centreline and waypoints optional, on a transparent ground.",
    parameters: [
      n("distance", "Signed margin", "Offset distance; sign selects the side when one edge is shown.", -40, 40, -10000, 10000),
      n("routes", "Routes", "Number of route centerlines.", 1, 12, 1, 1000, 1, true), weight,
      n("turns", "Turns", "Number of waypoint intervals in each route.", 1, 32, 1, 1000, 1, true),
      n("amplitude", "Bend amplitude", "Vertical reach of each route's turns.", -130, 130, -10000, 10000),
      n("frequency", "Bend cycles", "Oscillations across the canvas; negative values reverse progression.", -3, 5, -1000, 1000, .05),
      n("phase", "Bend phase", "Starting angle of route bends in degrees.", -180, 180, -1_000_000, 1_000_000),
      n("routeSpacing", "Route spacing", "Vertical distance between centerlines.", -160, 160, -10000, 10000),
      n("iterations", "Route smoothing", "Chaikin passes applied before offsetting.", 0, 5, 0, 16, 1, true),
      n("miterLimit", "Join limit", "Maximum pointed join length relative to margin before beveling.", 1, 8, 1, 1000, .1),
      toggle("showCenterline", "Show centerlines", "Draw the source route below its margin marks."),
      toggle("showEdges", "Show margin edges", "Draw offset route edges."),
      toggle("bothSides", "Both sides", "Draw the opposite offset edge as well."),
      toggle("showNodes", "Show waypoints", "Mark the route's original waypoints."),
    ],
    controlGroups: [
      { label: "Routes", stage: "form", controls: ["routes", "turns", "routeSpacing", "iterations"] },
      { label: "Bend", stage: "process", controls: ["frequency", "amplitude", "phase"] },
      { label: "Margins", stage: "process", controls: ["distance", "showEdges", "bothSides", "miterLimit"] },
      { label: "Drawing", stage: "material", controls: ["weight", "showCenterline", "showNodes"] },
    ],
    defaults: {distance: 12,
      routes: 5,
      weight: 2,
      turns: 10,
      amplitude: 46,
      frequency: 1.25,
      phase: 15,
      routeSpacing: 103,
      iterations: 2,
      miterLimit: 2,
      showCenterline: false,
      showEdges: true,
      bothSides: true,
      showNodes: false},
    validate: params => validatePathsAQuality("road-margins", params),
  },
  "nested-contour-strokes": {
    id: "nested-contour-strokes", title: "Nested contour strokes", description: "Offset an editable closed outline into contour rings.",
    procedure: "Build a closed polygon from the shape controls, then offset it to several signed distances, each ring stepping a fixed gap further than the last. Draw each offset path as an outline or as vertex dots; the rings are independent and may cross.",
    parameters: [
      n("distance", "Signed ring gap", "Actual distance between successive offsets; negative values reverse direction.", -40, 40, -10000, 10000),
      n("rings", "Rings", "Number of contours drawn from the source boundary.", 1, 16, 1, 1000, 1, true), weight,
      ...sourceShape,
      n("scale", "Boundary radius", "Size of the source outline before offsetting.", 50, 280, .01, 10000),
      n("startOffset", "Starting offset", "Offset distance of the first ring from the source.", -100, 100, -10000, 10000),
      n("miterLimit", "Join limit", "Maximum pointed join length before beveling.", 1, 8, 1, 1000, .1),
      choice("marks", "Ring marks", "Draw contours, their vertices, or both.", ["outline", "dots", "both"]),
      n("dotSize", "Vertex size", "Diameter of the contour vertex marks.", 0, 12, 0, 1000, .25),
      n("alpha", "Mark opacity", "Opacity of ring outlines and vertices.", 0, 255, 0, 255, 1, true),
    ],
    controlGroups: [
      { label: "Boundary", stage: "form", controls: ["scale", outlineShape] },
      { label: "Rings", stage: "material", controls: ["rings", "distance", "startOffset", "miterLimit"] },
      { label: "Drawing", stage: "material", controls: ["marks", { label: "Scale", controls: ["weight", "dotSize"], proportional: true }, "alpha"] },
    ],
    defaults: {distance: 12,
      rings: 8,
      weight: 2,
      sides: 7,
      notch: .25,
      aspect: .85,
      rotation: 12,
      scale: 198,
      startOffset: 0,
      miterLimit: 2,
      marks: "outline",
      dotSize: 4,
      alpha: 190},
    validate: params => validatePathsAQuality("nested-contour-strokes", params),
  },
};
for (const [id, kind, sides, innerRadius, scale, grain, weightValue] of [
  ["faceted-silhouettes", "convex", 7, .65, 205, 16, 2],
  ["concave-grain", "notched", 6, .48, 215, 24, 1.5],
] as const) {
  modern[id] = {
    id, title: id === "concave-grain" ? "Concave grain" : "Faceted silhouettes",
    description: "Triangulate an editable convex or notched boundary, then treat its facets independently.",
    procedure: id === "concave-grain" ? "Build a polygon with inward-notched corners, triangulate it into straight facets and fill each triangle with a palette colour. Draw the facet edges and add fan lines or dots inside every triangle as grain, leaving the ground transparent." : "Start from a convex polygon, triangulate it into straight facets and fill each triangle with its own palette colour. Outline the facets and add fan lines or dots inside each triangle as grain, leaving the ground transparent.",
    parameters: [
      n("scale", "Boundary radius", "Outer reach of the silhouette.", 60, 280, .01, 10000),
      n("grain", "Grain marks", "Fan lines or dots in each triangle.", 0, 60, 0, 1000, 1, true), weight,
      choice("kind", "Boundary", "Choose convex or radially notched source geometry.", ["convex", "notched"]),
      n("sides", "Outer sides", "Number of outer corners; notched shapes add one inner corner between each pair.", 3, 12, 3, 256, 1, true),
      n("innerRadius", "Notch radius", "Inner corner radius as a fraction of the outer radius; used for notched boundaries.", .1, .9, .01, 1, .01),
      n("aspect", "Height ratio", "Stretches the boundary vertically.", .3, 2, .01, 100, .01),
      n("rotation", "Rotation", "Turns the silhouette in degrees.", -180, 180, -1_000_000, 1_000_000),
      n("fillAlpha", "Facet fill", "Opacity of each filled triangle; zero leaves only marks.", 0, 255, 0, 255, 1, true),
      toggle("showEdges", "Show facet edges", "Trace the triangular facet boundaries."),
      choice("hatchMode", "Grain treatment", "Draw fan hatching, dots, or no grain marks.", ["fan", "dots", "none"]),
      n("hatchAlpha", "Grain opacity", "Opacity of facet-local grain marks.", 0, 255, 0, 255, 1, true),
    ],
    controlGroups: [
      { label: "Boundary", stage: "form", controls: ["kind", "sides", "innerRadius", "scale", "aspect", "rotation"] },
      { label: "Grain", stage: "material", controls: ["hatchMode", "grain"] },
      { label: "Drawing", stage: "material", controls: ["weight", "showEdges", { label: "Opacity", controls: ["fillAlpha", "hatchAlpha"], proportional: true }] },
    ],
    defaults: {scale,
      grain,
      weight: weightValue,
      kind,
      sides,
      innerRadius,
      aspect: .9,
      rotation: 12,
      fillAlpha: 115,
      showEdges: true,
      hatchMode: "fan",
      hatchAlpha: 165},
    validate: params => validatePathsAQuality(id, params),
  };
}
export const pathsADefinitions: StudioDefinition[] = specs.map(([id, title, description, first, second]) =>
  modern[id] ?? { id, title, description, parameters: [numeric(first[0], first[1], `Changes ${first[1].toLowerCase()} in this composition.`, first[2], first[3], first[4]), numeric(second[0], second[1], `Changes ${second[1].toLowerCase()} in this composition.`, second[2], second[3], second[4]), numeric("weight", "Stroke weight", "Outline width in pixels.", .5, 6, .25)], controlGroups: [{ label: "Composition", stage: "form", controls: [first[0], second[0], "weight"] }], defaults: pathsASettings[id as keyof typeof pathsASettings].defaults });
const draws: Record<string, (p: Parameters<typeof drawRoundedPanels>[0], layer: Layer) => void> = { "rounded-panels": drawRoundedPanels, "flowing-brushes": drawFlowingBrushes, "contour-abstraction": drawContourAbstraction, "gesture-skeletons": drawGestureSkeletons, "road-margins": drawRoadMargins, "nested-contour-strokes": drawNestedContourStrokes, "faceted-silhouettes": drawFacetedSilhouettes, "concave-grain": drawConcaveGrain };
export function drawPathsA(p: any, layer: Layer): void {
  const draw = draws[layer.technique];
  if (!draw) throw Error("Unknown paths A technique");
  if (["flowing-brushes", "contour-abstraction", "gesture-skeletons"].includes(layer.technique))
    drawPathGestures(p, layer);
  else if (modern[layer.technique]) drawPathsAQuality(p, layer);
  else draw(p, layer);
}
