import type { CompositionSurface } from "../composition/types.js";
import { drawReferenceComposition, referenceComposition } from "../composition/reference.js";
import type { InstrumentInput, InstrumentDefinition, Parameter } from "../types.js";
import { choice, numeric } from "./types.js";
import { mapNames } from "../composition/warp.js";

type Condition = Record<string, readonly (string | number | boolean)[]>;
function control(parameter: Parameter, group: string, visibleWhen?: Condition): Parameter {
  return { ...parameter, group, ...(visibleWhen ? { visibleWhen } : {}) };
}
const integerKeys: Record<string, true> = {
  maxPoints: true, petals: true, resolution: true, hillCount: true, levels: true,
  beadPetals: true, grid: true, attempts: true, markPetals: true, columns: true, rows: true, depth: true, iterations: true,
};
const n = (key: string, label: string, description: string, min: number, max: number, step: number,
  hardMin: number, hardMax: number, group: string, visibleWhen?: Condition): Parameter =>
  control(numeric(key, label, description, min, max, step,
    { hardMin, hardMax, integer: integerKeys[key] === true }), group, visibleWhen);
const select = (key: string, label: string, description: string, options: string[], group: string,
  visibleWhen?: Condition): Parameter => control(choice(key, label, description, options), group, visibleWhen);

const pointMarks = ["dot", "rings", "rosette", "arrow"];
const materials = ["ink", "stitch", "beads"];
export const referenceDefinitions: InstrumentDefinition[] = [
  {
    id: "motif-ecologies", title: "Motif Ecologies",
    description: "A positioned, editable ecology of open rings, dots and radial rosettes.",
    renderer: "2d",
    parameters: [
      n("centerX", "Center X", "Horizontal population center in canvas units.", 80, 560, 1, -320, 960, "Source"),
      n("centerY", "Center Y", "Vertical population center in canvas units.", 80, 560, 1, -320, 960, "Source"),
      n("width", "Width", "Population footprint width.", 80, 540, 1, 1, 1600, "Source"),
      n("height", "Height", "Population footprint height.", 80, 540, 1, 1, 1600, "Source"),
      n("separation", "Separation", "Minimum center spacing; larger values make airier populations.", 9, 90, 1, 1, 1600, "Source"),
      n("maxPoints", "Population cap", "Maximum generated sites before support filtering.", 0, 240, 1, 0, 600, "Source"),
      select("support", "Support", "Rectangle, ellipse or ring-shaped population.", ["rectangle", "ellipse", "annulus"], "Source"),
      n("opening", "Support opening", "Relative hole in annular support.", 0, .85, .01, 0, .98, "Source", { support: ["annulus"] }),
      n("rotation", "Support angle", "Source footprint orientation in degrees.", -180, 180, 1, -360, 360, "Source"),
      select("mark", "Mark", "Swap the same sites between dots, open rings, rosettes and arrows.", pointMarks, "Mark"),
      n("size", "Mark diameter", "Nominal diameter of each mark.", 1, 75, .5, 0, 500, "Mark"),
      n("petals", "Petals", "Number of radial strokes in each rosette.", 3, 18, 1, 1, 48, "Mark", { mark: ["rosette"] }),
      n("markOpening", "Interior opening", "Rosette empty center or inner ring offset.", 0, .9, .01, 0, 1, "Mark", { mark: ["rings", "rosette"] }),
      n("variation", "Size variation", "Stable size variation at each site.", 0, 1, .01, 0, 1, "Mark"),
      n("retention", "Mark retention", "Omit sites without moving the underlying population.", 0, 1, .01, 0, 1, "Mark"),
      n("weight", "Line weight", "Outline, petal and arrow stroke width.", .2, 5, .05, 0, 50, "Mark", { mark: ["rings", "rosette", "arrow"] }),
    ],
    defaults: { centerX: 320, centerY: 320, width: 470, height: 410, separation: 32, maxPoints: 135,
      support: "annulus", opening: .28, rotation: 22, mark: "rosette", size: 58, petals: 13,
      markOpening: .3, variation: .64, retention: .91, weight: 1.25 },
  },
  {
    id: "contour-scores", title: "Contour Scores",
    description: "A sampled scalar landscape written as continuous ink, tangent stitches or bead marks.",
    renderer: "2d",
    parameters: [
      select("source", "Field", "Switch noise, hills, waves or a saddle without changing the material.", ["noise", "hills", "waves", "saddle"], "Source"),
      n("centerX", "Center X", "Horizontal contour center.", 80, 560, 1, -320, 960, "Source"),
      n("centerY", "Center Y", "Vertical contour center.", 80, 560, 1, -320, 960, "Source"),
      n("width", "Width", "Landscape footprint width.", 80, 560, 1, 1, 2400, "Source"),
      n("height", "Height", "Landscape footprint height.", 80, 560, 1, 1, 2400, "Source"),
      n("resolution", "Grid resolution", "Field samples on each side; changes contour detail.", 12, 70, 1, 2, 78, "Source"),
      n("frequency", "Frequency", "Wave cycles or noise scale across the footprint.", .3, 5, .05, 0, 20, "Source", { source: ["noise", "waves"] }),
      n("aspect", "Field aspect", "Stretches field coordinates to vary the score's gesture.", .25, 3, .05, .1, 8, "Source"),
      n("hillCount", "Hill count", "Number of seeded hills.", 1, 16, 1, 1, 24, "Source", { source: ["hills"] }),
      n("hillRadius", "Hill radius", "Fraction of the footprint width covered by each hill.", .08, .5, .01, .01, 2, "Source", { source: ["hills"] }),
      n("levelBase", "First threshold", "Shifts which bands of the field produce paths.", -1, 1, .05, -16, 16, "Source"),
      n("levelStep", "Threshold interval", "Distance in field value between successive contours.", .05, .75, .005, .001, 16, "Source"),
      n("levels", "Threshold count", "Number of threshold slices.", 0, 12, 1, 0, 32, "Source"),
      n("rotation", "Landscape angle", "Rotate the contour footprint in degrees.", -180, 180, 1, -360, 360, "Source"),
      select("material", "Path material", "Read exactly the same paths as ink, stitches or beads.", materials, "Material"),
      n("weight", "Stroke weight", "Ink/stitch line thickness.", .2, 5, .1, 0, 50, "Material", { material: ["ink", "stitch"] }),
      n("spacing", "Station spacing", "Distance between stitch or bead stations.", 4, 45, .5, .5, 1000, "Material", { material: ["stitch", "beads"] }),
      n("phase", "Station phase", "Slides stations along a path by a fraction of their spacing.", 0, 1, .01, 0, 1, "Material", { material: ["stitch", "beads"] }),
      n("phaseSpread", "Cross-path phase", "Stable spread of station phase between paths.", 0, 1, .01, 0, 1, "Material", { material: ["stitch", "beads"] }),
      n("levelRamp", "Band size ramp", "Shrink bead marks from the first toward the last contour band.", 0, 1, .01, 0, 1, "Material", { material: ["beads"] }),
      n("retention", "Path retention", "Stable omission of paths or their stations.", 0, 1, .01, 0, 1, "Material"),
      select("beadMark", "Bead motif", "Nested point vocabulary on each contour station.", pointMarks, "Material/Bead mark", { material: ["beads"] }),
      n("beadSize", "Bead diameter", "Size of each bead motif.", 1, 26, .5, 0, 500, "Material/Bead mark", { material: ["beads"] }),
      n("beadPetals", "Bead petals", "Radial strokes in rosette beads.", 3, 14, 1, 1, 48, "Material/Bead mark", { material: ["beads"], beadMark: ["rosette"] }),
      n("beadWeight", "Bead line weight", "Thickness of ring outlines, rosette petals and arrows.", .2, 3, .1, 0, 50, "Material/Bead mark", { material: ["beads"], beadMark: ["rings", "rosette", "arrow"] }),
      n("beadOpening", "Bead opening", "Open center of rosettes or inner ring offset.", 0, .9, .01, 0, 1, "Material/Bead mark", { material: ["beads"], beadMark: ["rings", "rosette"] }),
    ],
    defaults: { source: "noise", centerX: 320, centerY: 320, width: 474, height: 460, resolution: 54,
      frequency: 3.1, aspect: 1.5, hillCount: 5, hillRadius: .23, levelBase: -.55,
      levelStep: .085, levels: 12, rotation: 12, material: "stitch", weight: 1.4,
      spacing: 8, phase: .35, phaseSpread: 0, levelRamp: 0, retention: .93,
      beadMark: "rings", beadSize: 7, beadPetals: 6, beadWeight: 1, beadOpening: .42 },
  },
  {
    id: "region-quilts", title: "Region Quilts",
    description: "Binary partitions filled by hatch lines, point ecologies or contour scores.",
    renderer: "2d",
    parameters: [
      n("centerX", "Center X", "Horizontal quilt center.", 80, 560, 1, -320, 960, "Source"),
      n("centerY", "Center Y", "Vertical quilt center.", 80, 560, 1, -320, 960, "Source"),
      n("width", "Width", "Partition footprint width.", 80, 560, 1, 1, 1000, "Source"),
      n("height", "Height", "Partition footprint height.", 80, 560, 1, 1, 1000, "Source"),
      n("grid", "Cut grid", "Discrete cut coordinates on each side of the rectangular footprint.", 2, 55, 1, 2, 150, "Source"),
      n("attempts", "Cut attempts", "Attempt-bounded seeded binary subdivisions.", 0, 85, 1, 0, 400, "Source"),
      select("axis", "Cut axis", "Longest-side or random choice of cut direction.", ["LONGEST", "RANDOM"], "Source"),
      n("bias", "Subdivision bias", "Negative gives balanced leaves; positive contrasts areas.", -1, 1, .01, -1, 1, "Source"),
      select("fill", "Leaf filler", "Use one vocabulary throughout or explicitly mix three.", ["hatch", "motifs", "contours", "mixed"], "Filler"),
      n("inset", "Inset", "Clearance inside each retained rectangular leaf.", 0, 30, .5, 0, 500, "Filler"),
      n("retention", "Leaf retention", "Stable omission without changing any partition cut.", 0, 1, .01, 0, 1, "Filler"),
      n("spacing", "Source spacing", "Hatch interval or nested motif separation.", 3, 60, .5, 1, 1000, "Filler", { fill: ["hatch", "motifs", "mixed"] }),
      n("angle", "Hatch direction", "Hatch angle, in degrees.", -90, 90, 1, -360, 360, "Filler", { fill: ["hatch", "mixed"] }),
      n("weight", "Line weight", "Shared thickness for hatches, contours, motif outlines and petals; filled dots have no outline.", .2, 5, .1, 0, 50, "Filler"),
      select("mark", "Nested motif", "Point mark used in motif-filled leaves.", pointMarks, "Filler/Motif", { fill: ["motifs", "mixed"] }),
      n("markSize", "Nested mark size", "Diameter of the nested point motif.", 2, 32, .5, 0, 500, "Filler/Motif", { fill: ["motifs", "mixed"] }),
      n("markPetals", "Nested petals", "Number of petals when nested motif is a rosette.", 3, 14, 1, 1, 48, "Filler/Motif", { fill: ["motifs", "mixed"], mark: ["rosette"] }),
      select("contourField", "Nested field", "Replace the field inside each leaf without changing the partition or its material.", ["noise", "hills", "waves", "saddle"], "Filler/Contour", { fill: ["contours", "mixed"] }),
      n("contourFrequency", "Nested field frequency", "Spatial frequency, or hill placement offset, within each leaf.", .3, 5, .05, .1, 12, "Filler/Contour", { fill: ["contours", "mixed"] }),
      select("material", "Nested contour material", "Material used on the nested leaf-local contours.", materials, "Filler/Contour", { fill: ["contours", "mixed"] }),
      n("materialSpacing", "Nested station spacing", "Spacing of contour stitches or beads.", 4, 36, .5, .5, 1000, "Filler/Contour", { fill: ["contours", "mixed"], material: ["stitch", "beads"] }),
      select("beadMark", "Nested bead motif", "Mark applied at each nested contour station.", pointMarks, "Filler/Contour/Bead mark", { fill: ["contours", "mixed"], material: ["beads"] }),
      n("beadSize", "Nested bead size", "Diameter of a contour bead.", 2, 22, .5, 0, 500, "Filler/Contour/Bead mark", { fill: ["contours", "mixed"], material: ["beads"] }),
      n("beadPetals", "Nested bead petals", "Number of rosette bead petals.", 3, 14, 1, 1, 48, "Filler/Contour/Bead mark", { fill: ["contours", "mixed"], material: ["beads"], beadMark: ["rosette"] }),
    ],
    defaults: { centerX: 320, centerY: 320, width: 475, height: 475, grid: 38,
      attempts: 22, axis: "LONGEST", bias: -.27, fill: "mixed", inset: 5,
      retention: .87, spacing: 13, angle: -35, weight: 1.5,
      mark: "rosette", markSize: 15, markPetals: 7,
      contourField: "noise", contourFrequency: 1.8,
      material: "ink", materialSpacing: 13, beadMark: "dot", beadSize: 6, beadPetals: 7 },
  },
  {
    id: "wallpaper-motifs", title: "Wallpaper Motifs",
    description: "A stated plane symmetry group stamps one motif across the plane, with stable breaking.",
    renderer: "2d",
    parameters: [
      select("group", "Symmetry group", "One of the seventeen plane groups; changes the instance lattice and operations.",
        ["p1", "p2", "pm", "pg", "cm", "pmm", "pmg", "pgg", "cmm", "p4", "p4m", "p4g", "p3", "p3m1", "p31m", "p6", "p6m"], "Source"),
      n("cellWidth", "Cell width", "First lattice vector length in canvas units.", 16, 220, 1, 4, 4096, "Source"),
      n("cellHeight", "Cell height", "Second lattice vector length; square and hexagonal groups use the cell width alone.", 16, 220, 1, 4, 4096, "Source",
        { group: ["p1", "p2", "pm", "pg", "cm", "pmm", "pmg", "pgg", "cmm"] }),
      n("centerX", "Center X", "Horizontal viewport center.", 80, 560, 1, -320, 960, "Source"),
      n("centerY", "Center Y", "Vertical viewport center.", 80, 560, 1, -320, 960, "Source"),
      n("width", "Viewport width", "Canvas width over which the pattern is shown.", 80, 640, 1, 1, 1600, "Source"),
      n("height", "Viewport height", "Canvas height over which the pattern is shown.", 80, 640, 1, 1, 1600, "Source"),
      n("motifOffsetX", "Motif offset X", "Motif anchor as a fraction of the unit cell.", 0, 1, .01, 0, 1, "Source"),
      n("motifOffsetY", "Motif offset Y", "Motif anchor as a fraction of the unit cell.", 0, 1, .01, 0, 1, "Source"),
      n("margin", "Viewport margin", "Instances this far past the edge remain visible.", 0, 120, 1, 0, 512, "Source"),
      n("breakAmount", "Breaking amount", "Bounded position, rotation and scale deviation of broken instances.", 0, 1, .01, 0, 1, "Break"),
      n("breakDensity", "Breaking density", "Stable fraction of instances that break the symmetry.", 0, 1, .01, 0, 1, "Break"),
      select("mark", "Mark", "Swap the same instances between dots, rings, rosettes and arrows.", pointMarks, "Mark"),
      n("size", "Mark diameter", "Nominal diameter of each mark.", 1, 75, .5, 0, 500, "Mark"),
      n("petals", "Petals", "Radial strokes in each rosette.", 3, 18, 1, 1, 48, "Mark", { mark: ["rosette"] }),
      n("markOpening", "Interior opening", "Rosette empty center or inner ring offset.", 0, .9, .01, 0, 1, "Mark", { mark: ["rings", "rosette"] }),
      n("variation", "Size variation", "Stable size variation at each site.", 0, 1, .01, 0, 1, "Mark"),
      n("retention", "Instance retention", "Omit instances without moving the underlying lattice.", 0, 1, .01, 0, 1, "Mark"),
      n("weight", "Line weight", "Outline, petal and arrow stroke width.", .2, 5, .05, 0, 50, "Mark", { mark: ["rings", "rosette", "arrow"] }),
    ],
    defaults: { group: "p4g", cellWidth: 140, cellHeight: 140, centerX: 320, centerY: 320,
      width: 640, height: 640, motifOffsetX: .22, motifOffsetY: .12, margin: 40,
      breakAmount: .1, breakDensity: .1, mark: "arrow", size: 42, petals: 8,
      markOpening: .34, variation: 0, retention: 1, weight: 1.7 },
  },
  {
    id: "ordered-disorder", title: "Ordered Disorder",
    description: "A regular lattice under a shared correlated field of displacement, rotation, scale and omission.",
    renderer: "2d",
    parameters: [
      n("columns", "Columns", "Lattice columns.", 3, 40, 1, 2, 96, "Source"),
      n("rows", "Rows", "Lattice rows.", 3, 40, 1, 2, 96, "Source"),
      n("centerX", "Center X", "Horizontal lattice center.", 80, 560, 1, -320, 960, "Source"),
      n("centerY", "Center Y", "Vertical lattice center.", 80, 560, 1, -320, 960, "Source"),
      n("width", "Width", "Lattice footprint width.", 80, 560, 1, 1, 1600, "Source"),
      n("height", "Height", "Lattice footprint height.", 80, 560, 1, 1, 1600, "Source"),
      n("correlation", "Correlation length", "Disorder correlation in cells; larger keeps neighbors alike.", 1, 30, .5, 1, 64, "Source"),
      n("focalX", "Focal X", "Horizontal center of the disorder focal region.", 0, 640, 1, -320, 960, "Source"),
      n("focalY", "Focal Y", "Vertical center of the disorder focal region.", 0, 640, 1, -320, 960, "Source"),
      n("focalRadius", "Focal radius", "Distance over which disorder fades smoothly from full strength at the focus to none; zero applies it everywhere.", 0, 640, 1, 0, 4096, "Source"),
      n("displacement", "Displacement", "Maximum site shift as a fraction of the cell.", 0, .95, .01, 0, 1, "Disorder"),
      n("rotation", "Rotation", "Maximum stable rotation in degrees. Round marks do not visibly turn, but sites turned past 70% of it still count as strongly disturbed and take the second color.", 0, 180, 1, 0, 360, "Disorder"),
      n("scale", "Scale wobble", "Maximum relative scale deviation.", 0, .9, .01, 0, 1, "Disorder"),
      n("omission", "Omission", "Correlated omission threshold; omissions form runs.", 0, .8, .01, 0, 1, "Disorder"),
      n("anchors", "Anchors", "Stable fraction of sites pinned to their exact grid origin.", 0, 1, .01, 0, 1, "Disorder"),
      n("retention", "Site retention", "Stable per-site omission independent of the field.", 0, 1, .01, 0, 1, "Disorder"),
      select("mark", "Mark", "Swap the same sites between dots, rings, rosettes and arrows.", pointMarks, "Mark"),
      n("size", "Mark diameter", "Nominal diameter of each mark.", 1, 60, .5, 0, 500, "Mark"),
      n("petals", "Petals", "Radial strokes in each rosette.", 3, 18, 1, 1, 48, "Mark", { mark: ["rosette"] }),
      n("markOpening", "Interior opening", "Rosette empty center or inner ring offset.", 0, .9, .01, 0, 1, "Mark", { mark: ["rings", "rosette"] }),
      n("variation", "Size variation", "Stable size variation at each site.", 0, 1, .01, 0, 1, "Mark"),
      n("weight", "Line weight", "Outline, petal and arrow stroke width.", .2, 5, .05, 0, 50, "Mark", { mark: ["rings", "rosette", "arrow"] }),
    ],
    defaults: { columns: 14, rows: 14, centerX: 320, centerY: 320, width: 520, height: 520,
      correlation: 4, focalX: 380, focalY: 280, focalRadius: 420,
      displacement: .6, rotation: 60, scale: .45, omission: .22, anchors: .06, retention: 1,
      mark: "rings", size: 30, petals: 8, markOpening: .3, variation: .3, weight: 1.5 },
  },
  {
    id: "recursive-cells", title: "Recursive Cell Worlds",
    description: "Nested compartments grown by bounded recursive subdivision, filled like region quilts.",
    renderer: "2d",
    parameters: [
      n("centerX", "Center X", "Horizontal world center.", 80, 560, 1, -320, 960, "Source"),
      n("centerY", "Center Y", "Vertical world center.", 80, 560, 1, -320, 960, "Source"),
      n("width", "Width", "World footprint width.", 80, 560, 1, 1, 1000, "Source"),
      n("height", "Height", "World footprint height.", 80, 560, 1, 1, 1000, "Source"),
      n("depth", "Max depth", "Levels of recursive subdivision.", 1, 7, 1, 1, 12, "Source"),
      n("minSize", "Min leaf size", "Nodes with a shorter side stop subdividing.", 14, 160, 1, 0, 8192, "Source"),
      n("stopChance", "Early stopping", "Stable fraction of nodes that stop growing.", 0, .9, .01, 0, 1, "Source"),
      n("childRetention", "Child retention", "Stable probability each child branch is kept.", 0, 1, .01, 0, 1, "Source"),
      select("axis", "Cut axis", "Longest-side or random choice of cut direction.", ["LONGEST", "RANDOM"], "Source"),
      n("bias", "Subdivision bias", "Negative gives balanced leaves; positive contrasts areas.", -1, 1, .01, -1, 1, "Source"),
      select("fill", "Leaf filler", "Use one vocabulary throughout or explicitly mix three.", ["hatch", "motifs", "contours", "mixed"], "Filler"),
      n("inset", "Inset", "Clearance inside each retained terminal leaf.", 0, 30, .5, 0, 500, "Filler"),
      n("retention", "Leaf retention", "Stable omission without changing any subdivision cut.", 0, 1, .01, 0, 1, "Filler"),
      n("spacing", "Source spacing", "Hatch interval or nested motif separation.", 3, 60, .5, 1, 1000, "Filler", { fill: ["hatch", "motifs", "mixed"] }),
      n("angle", "Hatch direction", "Hatch angle, in degrees.", -90, 90, 1, -360, 360, "Filler", { fill: ["hatch", "mixed"] }),
      n("weight", "Line weight", "Shared thickness for hatches, contours, motif outlines and petals; filled dots have no outline.", .2, 5, .1, 0, 50, "Filler"),
      select("mark", "Nested motif", "Point mark used in motif-filled leaves.", pointMarks, "Filler/Motif", { fill: ["motifs", "mixed"] }),
      n("markSize", "Nested mark size", "Diameter of the nested point motif.", 2, 32, .5, 0, 500, "Filler/Motif", { fill: ["motifs", "mixed"] }),
      n("markPetals", "Nested petals", "Number of petals when nested motif is a rosette.", 3, 14, 1, 1, 48, "Filler/Motif", { fill: ["motifs", "mixed"], mark: ["rosette"] }),
      select("contourField", "Nested field", "Replace the field inside each leaf without changing the subdivision or its material.", ["noise", "hills", "waves", "saddle"], "Filler/Contour", { fill: ["contours", "mixed"] }),
      n("contourFrequency", "Nested field frequency", "Spatial frequency, or hill placement offset, within each leaf.", .3, 5, .05, .1, 12, "Filler/Contour", { fill: ["contours", "mixed"] }),
      select("material", "Nested contour material", "Material used on the nested leaf-local contours.", materials, "Filler/Contour", { fill: ["contours", "mixed"] }),
      n("materialSpacing", "Nested station spacing", "Spacing of contour stitches or beads.", 4, 36, .5, .5, 1000, "Filler/Contour", { fill: ["contours", "mixed"], material: ["stitch", "beads"] }),
      select("beadMark", "Nested bead motif", "Mark applied at each nested contour station.", pointMarks, "Filler/Contour/Bead mark", { fill: ["contours", "mixed"], material: ["beads"] }),
      n("beadSize", "Nested bead size", "Diameter of a contour bead.", 2, 22, .5, 0, 500, "Filler/Contour/Bead mark", { fill: ["contours", "mixed"], material: ["beads"] }),
      n("beadPetals", "Nested bead petals", "Number of rosette bead petals.", 3, 14, 1, 1, 48, "Filler/Contour/Bead mark", { fill: ["contours", "mixed"], material: ["beads"], beadMark: ["rosette"] }),
    ],
    defaults: { centerX: 320, centerY: 320, width: 560, height: 560, depth: 6, minSize: 38,
      stopChance: .12, childRetention: .92, axis: "LONGEST", bias: -.2,
      fill: "mixed", inset: 4, retention: .95, spacing: 12, angle: -30, weight: 1.4,
      mark: "rosette", markSize: 14, markPetals: 7,
      contourField: "noise", contourFrequency: 1.9,
      material: "ink", materialSpacing: 12, beadMark: "dot", beadSize: 6, beadPetals: 7 },
  },
  {
    id: "fold-atlas", title: "Fold Atlas",
    description: "A grid pushed through chained coordinate maps: folds, swirls, seams and pinched centers, with lines and nodes following the same mapping.",
    renderer: "2d",
    parameters: [
      n("centerX", "Grid center X", "Horizontal center of the source grid.", 80, 560, 1, -320, 960, "Grid"),
      n("centerY", "Grid center Y", "Vertical center of the source grid.", 80, 560, 1, -320, 960, "Grid"),
      n("width", "Grid width", "Width of the source grid before mapping.", 80, 640, 1, 1, 4096, "Grid"),
      n("height", "Grid height", "Height of the source grid before mapping.", 80, 640, 1, 1, 4096, "Grid"),
      n("columns", "Columns", "Vertical grid lines: one more than this number.", 2, 40, 1, 1, 60, "Grid"),
      n("rows", "Rows", "Horizontal grid lines: one more than this number.", 2, 40, 1, 1, 60, "Grid"),
      n("jitter", "Grid irregularity", "Stable per-line shift of the interior lines, up to 45% of a spacing; a new seed reshuffles it. The edge lines stay put.", 0, 1, .01, 0, 1, "Grid"),
      n("mapCenterX", "Map center X", "Fixed point of every map, horizontally.", 0, 640, 1, -640, 1280, "Map"),
      n("mapCenterY", "Map center Y", "Fixed point of every map, vertically.", 0, 640, 1, -640, 1280, "Map"),
      n("mapRadius", "Map radius", "Canvas length the maps treat as 1; smaller values apply them more strongly.", 60, 480, 1, 1, 4096, "Map"),
      select("stage1Map", "First map", "Sinusoidal folds, swirl twists, fisheye compresses, spherical inverts about the center, polar unrolls, handkerchief drapes, waves ripple and horseshoe reflects.", mapNames as string[], "Map/First"),
      n("stage1Amount", "First amount", "Blend from no change (0) to the full map (1); above 1 exaggerates it.", 0, 1.5, .01, 0, 2, "Map/First"),
      n("stage1Frequency", "First frequency", "The map's coefficient: fold count, twist rate or scale.", .25, 6, .05, .05, 12, "Map/First"),
      select("stage2Map", "Second map", "Applied after the first map to its result.", mapNames as string[], "Map/Second"),
      n("stage2Amount", "Second amount", "Blend from no change to the full map; zero skips this stage.", 0, 1.5, .01, 0, 2, "Map/Second"),
      n("stage2Frequency", "Second frequency", "The second map's coefficient.", .25, 6, .05, .05, 12, "Map/Second"),
      select("stage3Map", "Third map", "Applied after the second map to its result.", mapNames as string[], "Map/Third"),
      n("stage3Amount", "Third amount", "Blend from no change to the full map; zero skips this stage.", 0, 1.5, .01, 0, 2, "Map/Third"),
      n("stage3Frequency", "Third frequency", "The third map's coefficient.", .25, 6, .05, .05, 12, "Map/Third"),
      n("iterations", "Repeat chain", "Run the whole chain again on its own output; order matters.", 1, 4, 1, 1, 4, "Map"),
      n("bound", "Exclusion bound", "Points sent farther than this many radii from the map center are dropped, which is how singular maps leave a hole instead of runaway lines.", 2, 20, .5, 1, 50, "Map"),
      select("material", "Line material", "Draw each mapped grid line as ink, stitches or beads.", materials, "Lines"),
      n("weight", "Line weight", "Ink and stitch line thickness.", .2, 5, .1, 0, 50, "Lines", { material: ["ink", "stitch"] }),
      n("spacing", "Station spacing", "Distance between stitch or bead stations along a mapped line.", 4, 45, .5, .5, 1000, "Lines", { material: ["stitch", "beads"] }),
      n("phase", "Station phase", "Slides stations along each line by a fraction of their spacing.", 0, 1, .01, 0, 1, "Lines", { material: ["stitch", "beads"] }),
      n("phaseSpread", "Cross-line phase", "Stable spread of station phase between lines, so neighbouring lines' stations stop lining up.", 0, 1, .01, 0, 1, "Lines", { material: ["stitch", "beads"] }),
      n("levelRamp", "Size ramp across the grid", "Shrink beads from the first grid line toward the last in each family.", 0, 1, .01, 0, 1, "Lines", { material: ["beads"] }),
      n("retention", "Line retention", "Stable omission of lines or their stations; zero leaves only the nodes.", 0, 1, .01, 0, 1, "Lines"),
      select("beadMark", "Bead motif", "Point vocabulary on each bead station.", pointMarks, "Lines/Bead mark", { material: ["beads"] }),
      n("beadSize", "Bead diameter", "Size of each bead motif.", 1, 26, .5, 0, 500, "Lines/Bead mark", { material: ["beads"] }),
      n("beadPetals", "Bead petals", "Radial strokes in rosette beads.", 3, 14, 1, 1, 48, "Lines/Bead mark", { material: ["beads"], beadMark: ["rosette"] }),
      n("beadWeight", "Bead line weight", "Thickness of ring outlines, rosette petals and arrows.", .2, 3, .1, 0, 50, "Lines/Bead mark", { material: ["beads"], beadMark: ["rings", "rosette", "arrow"] }),
      n("beadOpening", "Bead opening", "Open center of rosettes or inner ring offset.", 0, .9, .01, 0, 1, "Lines/Bead mark", { material: ["beads"], beadMark: ["rings", "rosette"] }),
      select("nodeMark", "Node mark", "The mark drawn at every grid crossing, carried through the mapping. Crossings the map turns inside out are mirrored and drawn in the second color.", pointMarks, "Nodes"),
      n("nodeSize", "Node size", "Diameter of each node mark before the map rescales it; zero hides the nodes.", 0, 30, .5, 0, 500, "Nodes"),
      n("nodePetals", "Node petals", "Radial strokes in rosette nodes.", 3, 14, 1, 1, 48, "Nodes", { nodeMark: ["rosette"] }),
      n("nodeOpening", "Node opening", "Open center of rosettes or inner ring offset.", 0, .9, .01, 0, 1, "Nodes", { nodeMark: ["rings", "rosette"] }),
      n("nodeWeight", "Node line weight", "Thickness of ring outlines, rosette petals and arrows.", .2, 3, .1, 0, 50, "Nodes", { nodeMark: ["rings", "rosette", "arrow"] }),
    ],
    defaults: { centerX: 320, centerY: 320, width: 500, height: 500, columns: 20, rows: 20, jitter: .6,
      mapCenterX: 320, mapCenterY: 320, mapRadius: 250,
      stage1Map: "swirl", stage1Amount: .9, stage1Frequency: 2,
      stage2Map: "sinusoidal", stage2Amount: .45, stage2Frequency: 1.3,
      stage3Map: "fisheye", stage3Amount: 0, stage3Frequency: 1,
      iterations: 1, bound: 8,
      material: "ink", weight: 1.1, spacing: 8, phase: .35, phaseSpread: 0, levelRamp: 0, retention: 1,
      beadMark: "dot", beadSize: 4, beadPetals: 6, beadWeight: 1, beadOpening: .4,
      nodeMark: "dot", nodeSize: 4, nodePetals: 6, nodeOpening: .4, nodeWeight: 1 },
  },
];

/** Draw a transparent 640-unit reference layer into the host-owned 2D surface. */
export function drawReferenceInstrument(surface: CompositionSurface, input: InstrumentInput): void {
  drawReferenceComposition(surface, referenceComposition(input));
}
