import type { Layer } from "../studio-types"; import { numeric,type StudioDefinition } from "./types";
import * as draws from "../../../../packages/javascript/examples/materials-a-studies.js";
const rows=[
["diffusion-engraving","Diffusion engraving","Error-diffused etched field.","scale",5,16,"threshold",.2,.8],["dithered-ribbons","Dithered ribbons","Directional dither marks.","scale",5,16,"threshold",.2,.8],["ordered-halftone","Ordered halftone","Bayer screen dots.","scale",5,16,"order",1,5],["bayer-weave","Bayer weave","Crossed ordered screen.","scale",6,20,"order",1,5],["embossed-field","Embossed field","Signed convolution relief.","scale",5,16,"gain",.4,3],["signed-edge-print","Signed edge print","Two-ink convolution edges.","scale",5,16,"gain",.4,3],["distance-halos","Distance halos","Nearest-feature rings.","scale",6,18,"radius",2,16],["nearest-feature-mosaic","Nearest feature mosaic","Voronoi-like nearest IDs.","scale",8,20,"features",4,30],["eroded-lace","Eroded lace","Shrunk binary motif.","scale",5,16,"passes",1,3],["dilated-stamps","Dilated stamps","Expanded binary motif.","scale",6,18,"passes",1,3],["perceptual-bands","Perceptual bands","OKLab color intervals.","bands",6,40,"phase",0,6.28],["oklab-orbits","OKLab orbits","Perceptual colored rings.","orbits",6,40,"phase",0,6.28],["reduced-mosaic","Reduced mosaic","Median-cut color tiles.","scale",12,20,"count",2,10],["quantized-stripes","Quantized stripes","Median-cut stripe palette.","stripes",8,52,"count",2,10]
] as const;
const label=(value:string)=>value.replace(/^./,c=>c.toUpperCase());const integer=new Set(["order","passes","count","features","bands","orbits","stripes"]);
export const materialsADefinitions:StudioDefinition[]=rows.map(([id,title,description,a,amin,amax,b,bmin,bmax])=>({id,title,description,parameters:[numeric(a,label(a),`Changes ${a}.`,amin,amax,integer.has(a)?1:.01),numeric(b,b==="count"?"Colors":label(b),`Changes ${b}.`,bmin,bmax,integer.has(b)?1:.01),...((id==="distance-halos"||id==="oklab-orbits")?[numeric("weight","Stroke weight","Thickness of the ring marks.",.5,4,.25)]:[])],defaults:draws.materialsASettings[id].defaults}));
const names={"diffusion-engraving":"drawDiffusionEngraving","dithered-ribbons":"drawDitheredRibbons","ordered-halftone":"drawOrderedHalftone","bayer-weave":"drawBayerWeave","embossed-field":"drawEmbossedField","signed-edge-print":"drawSignedEdgePrint","distance-halos":"drawDistanceHalos","nearest-feature-mosaic":"drawNearestFeatureMosaic","eroded-lace":"drawErodedLace","dilated-stamps":"drawDilatedStamps","perceptual-bands":"drawPerceptualBands","oklab-orbits":"drawOklabOrbits","reduced-mosaic":"drawReducedMosaic","quantized-stripes":"drawQuantizedStripes"} as const;
export function drawMaterialsA(p:any,layer:Layer):void{const name=names[layer.technique as keyof typeof names];const draw=(draws as any)[name];if(!draw)throw Error("Unknown materials A technique");draw(p,layer);}
