import { numeric, type StudioDefinition } from "./types";
export const pathsBDefinitions: StudioDefinition[] = [
 {id:"stitched-contours",title:"Stitched contours",description:"Joined contour-like chains.",parameters:[numeric("lines","Lines","Chain count.",3,20,1),numeric("waves","Waves","Bends per chain.",1,8,.5),numeric("weight","Weight","Stroke width.",.4,4,.1)],defaults:{lines:9,waves:3,weight:1.2}},
 {id:"fragmented-lines",title:"Fragmented lines",description:"Broken segment chains.",parameters:[numeric("lines","Lines","Line count.",3,30,1),numeric("gaps","Gap rhythm","Omitted-segment rhythm.",2,12,1),numeric("weight","Weight","Stroke width.",.4,4,.1)],defaults:{lines:18,gaps:4,weight:2}},
 {id:"blue-noise-stipple",title:"Blue-noise stipple",description:"Explicit-state spaced dots.",parameters:[numeric("radius","Spacing","Minimum dot distance.",6,40,1),numeric("size","Dot size","Dot diameter.",1,10,.5),numeric("attempts","Attempts","Candidates per active point.",2,12,1)],defaults:{radius:18,size:4,attempts:8}},
 {id:"spaced-symbols",title:"Spaced symbols",description:"Poisson-spaced square symbols.",parameters:[numeric("radius","Spacing","Minimum symbol distance.",8,45,1),numeric("size","Size","Symbol side.",3,24,1),numeric("attempts","Attempts","Candidates per active point.",2,12,1)],defaults:{radius:26,size:10,attempts:7}},
 {id:"relaxed-stones",title:"Relaxed stones",description:"Lloyd-relaxed Voronoi stones.",parameters:[numeric("sites","Sites","Initial site count.",4,50,1),numeric("iterations","Passes","Relaxation passes.",1,5,1),numeric("inset","Inset","Distance pulled toward each cell site.",1,8,.5)],defaults:{sites:24,iterations:2,inset:4}},
 {id:"centroid-trails",title:"Centroid trails",description:"Site movement through relaxation.",parameters:[numeric("sites","Sites","Initial site count.",4,40,1),numeric("iterations","Passes","Trail length.",1,7,1),numeric("weight","Weight","Trail width.",.3,4,.1)],defaults:{sites:18,iterations:3,weight:1}},
 {id:"packed-posters",title:"Packed posters",description:"Skyline-packed poster blocks.",parameters:[numeric("count","Blocks","Rectangle count.",4,45,1),numeric("scale","Scale","Rectangle scale.",.4,1.4,.05),numeric("outline","Outline","Border width.",0,5,.25)],defaults:{count:22,scale:1,outline:2}},
 {id:"aspect-tiles",title:"Aspect tiles",description:"Varied-aspect skyline tiles.",parameters:[numeric("count","Tiles","Rectangle count.",4,45,1),numeric("scale","Scale","Tile scale.",.4,1.4,.05),numeric("outline","Outline","Border width.",0,4,.25)],defaults:{count:25,scale:1,outline:1}},
 {id:"obstacle-roads",title:"Obstacle roads",description:"Shortest-path predecessor roads.",parameters:[numeric("columns","Columns","Grid columns.",8,40,1),numeric("rows","Rows","Grid rows.",8,40,1),numeric("weight","Weight","Road width.",.4,4,.1)],defaults:{columns:24,rows:24,weight:2}},
 {id:"arrival-contours",title:"Arrival contours",description:"Contours of path arrival cost.",parameters:[numeric("columns","Columns","Grid columns.",10,45,1),numeric("rows","Rows","Grid rows.",10,45,1),numeric("weight","Weight","Contour width.",.4,3,.1)],defaults:{columns:28,rows:28,weight:1.2}},
];
