#!/usr/bin/env python3
"""Regenerate CP9 shared vectors from the private exact work-schedule oracle.

The catalog owns semantics. This generator never imports public triangulation code.
Without --write, compare exact generated bytes and fail if the fixture is stale.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import struct
from fractions import Fraction
from pathlib import Path
from typing import Any

import contract_oracle as oracle

ROOT = Path(__file__).resolve().parents[3]
OUT = ROOT / "fixtures/operations/delaunay-2d.json"
DECISIONS = ROOT / "design/operations/cp9-triangulation-contract-decisions.md"
NUMERIC = ROOT / "design/operations/cp9-capacity-and-numeric-fixtures.md"
POLICY = ROOT / "design/operations/cp9-fixture-policy.md"
GEOMETRY = ROOT / "tools/diagnostics/cp9/topology_prototype.py"


def sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def repository_path(value: str, *, label: str) -> Path:
    """Resolve a required repo-relative regular file without permitting escape."""
    candidate = Path(value)
    if candidate.is_absolute() or ".." in candidate.parts:
        raise ValueError(label + " must be a repository-relative path")
    resolved = (ROOT / candidate).resolve()
    try:
        resolved.relative_to(ROOT)
    except ValueError as error:
        raise ValueError(label + " escapes the repository") from error
    return resolved


def bits(value: float) -> str:
    return struct.pack(">d", value).hex()


def canonical_float(value: Any) -> float:
    result = float(Fraction(value)) if isinstance(value, str) else float(value)
    return 0.0 if result == 0.0 else result


def projected_output(result: dict[str, Any]) -> tuple[dict[str, Any], dict[str, Any]]:
    """Keep the contract's seven output keys; put raw binary64 checks in comparison."""
    output = {key: result[key] for key in ("points", "inputToVertex", "sourceIndices", "triangles", "edges", "edgeFaces", "workUsed")}
    points = [[canonical_float(component) for component in pair] for pair in result["points"]]
    output["points"] = points
    comparison = {
        "mode": "binary64-exact",
        "points_bits_hex": [[bits(component) for component in pair] for pair in points],
    }
    return output, comparison


def success(identifier: str, config: dict[str, Any]) -> dict[str, Any]:
    result = oracle.triangulate(config)
    if result["triangles"]:
        verification = result["geometryVerification"]
        if not verification["two_dimensional"] or not verification["area_matches_hull"] or not verification["empty_circle"]:
            raise AssertionError("independent geometry verification failed: " + identifier)
    output, comparison = projected_output(result)
    return {"id": identifier, "input": config, "output": output, "comparison": comparison}


def error(identifier: str, config: dict[str, Any]) -> dict[str, Any]:
    row = oracle.attempt(identifier, config)
    if row["status"] != "error":
        raise AssertionError("expected error: " + identifier)
    result = {"id": identifier, "input": row["input"], "error": row["error"]}
    if "error_detail" in row:
        result["error_detail"] = row["error_detail"]
    return result


def known_points() -> list[list[float]]:
    return [[0.0, 0.0], [2.0, 0.0], [4.0, 0.0], [4.0, 2.0], [4.0, 4.0], [2.0, 4.0], [0.0, 4.0], [0.0, 2.0], [2.0, 2.0]]


def work_stage_cases() -> tuple[list[dict[str, Any]], dict[str, int]]:
    baseline = oracle.triangulate({"points": known_points(), "maxWork": oracle.WORK_LIMIT})
    first: dict[str, int] = {}
    for event in baseline["workTrace"]:
        first.setdefault(event["stage"], int(event["after"]))
    expected = ("canonicalize", "hull_lower", "hull_upper", "locate", "legalize")
    if tuple(first) != expected:
        raise AssertionError("draft schedule stage coverage changed: " + repr(tuple(first)))
    cases = [success("boundary-and-internal-edge-insertions-exact-budget", {"points": known_points(), "maxWork": baseline["workUsed"]})]
    for stage in expected:
        cases.append(error("one-short-" + stage, {"points": known_points(), "maxWork": first[stage] - 1}))
    cases.append(error("one-short-total", {"points": known_points(), "maxWork": baseline["workUsed"] - 1}))
    return cases, {
        "exact_work_used": int(baseline["workUsed"]),
        "first_charge_after": {stage: value for stage, value in first.items()},
        "one_short_max_work": {stage: value - 1 for stage, value in first.items()},
    }


def build(catalog: Path | None = None) -> dict[str, Any]:
    min_subnormal = float.fromhex("0x0.0000000000001p-1022")
    near_inside = -float.fromhex("0x1.ffffffffffffep-1")
    maximum = float.fromhex("0x1.fffffffffffffp+1023")
    work_cases, work_thresholds = work_stage_cases()
    duplicate_points = [[0.0, 0.0], [4.0, 0.0], [0.0, 4.0], [4.0, 4.0], [2.0, 2.0], [0.0, -0.0], [2.0, 2.0], [4.0, 0.0]]
    base_duplicate = success("duplicates-negative-zero", {"points": duplicate_points, "maxWork": oracle.WORK_LIMIT})
    reversed_duplicate = success("duplicates-reversed", {"points": list(reversed(duplicate_points)), "maxWork": oracle.WORK_LIMIT})
    rotated_duplicate = success("duplicates-rotated", {"points": duplicate_points[3:] + duplicate_points[:3], "maxWork": oracle.WORK_LIMIT})
    triangle_hand = success("triangle-hand-work-5", {"points": [[0.0, 0.0], [1.0, 0.0], [0.0, 1.0]], "maxWork": 5})
    square_hand = success("square-hand-work-9", {"points": [[0.0, 0.0], [1.0, 0.0], [1.0, 1.0], [0.0, 1.0]], "maxWork": 9})
    if triangle_hand["output"]["workUsed"] != 5 or triangle_hand["output"]["triangles"] != [[0, 2, 1]]:
        raise AssertionError("triangle hand-work policy diverged")
    if square_hand["output"]["workUsed"] != 9:
        raise AssertionError("square hand-work policy diverged")
    cases: list[dict[str, Any]] = [
        success("empty", {"points": [], "maxWork": 0}),
        success("single-site", {"points": [[1.0, 2.0]], "maxWork": 1}),
        success("two-sites", {"points": [[1.0, 2.0], [3.0, 4.0]], "maxWork": 2}),
        triangle_hand,
        square_hand,
        success("triangle-integral-floating-work-5", {"points": [[0.0, 0.0], [1.0, 0.0], [0.0, 1.0]], "maxWork": 5.0}),
        base_duplicate,
        reversed_duplicate,
        rotated_duplicate,
        success("all-identical-sites", {"points": [[1.0, 2.0], [1.0, 2.0], [1.0, 2.0]], "maxWork": 3}),
        success("all-collinear", {"points": [[float(index), 0.0] for index in range(8)], "maxWork": oracle.WORK_LIMIT}),
        success("interior-insertions", {"points": [[0.0, 0.0], [6.0, 0.0], [6.0, 6.0], [0.0, 6.0], [0.5, 1.0 / 3.0], [7.0 / 3.0, 2.5]], "maxWork": oracle.WORK_LIMIT}),
        success("cocircular-lex-flip", {"points": [[0.0, 0.0], [0.0, 1.0], [0.0, 2.0], [1.0, 2.0], [2.0, 2.0]], "maxWork": oracle.WORK_LIMIT}),
        success("minimum-subnormal-triangle", {"points": [[0.0, 0.0], [min_subnormal, 0.0], [0.0, min_subnormal]], "maxWork": oracle.WORK_LIMIT}),
        success("minimum-subnormal-square-cocircular", {"points": [[0.0, 0.0], [min_subnormal, 0.0], [min_subnormal, min_subnormal], [0.0, min_subnormal]], "maxWork": oracle.WORK_LIMIT}),
        success("integer-cancellation-triangle", {"points": [[0.0, 0.0], [134217729.0, 134217728.0], [134217728.0, 134217727.0]], "maxWork": oracle.WORK_LIMIT}),
        success("near-cocircular-inside", {"points": [[1.0, 0.0], [0.0, 1.0], [-1.0, 0.0], [0.0, near_inside]], "maxWork": oracle.WORK_LIMIT}),
        success("exact-unit-circle-cocircular", {"points": [[1.0, 0.0], [0.0, 1.0], [-1.0, 0.0], [0.0, -1.0]], "maxWork": oracle.WORK_LIMIT}),
        success("mixed-finite-extremes-incircle", {"points": [[-maximum, 0.0], [maximum, 0.0], [0.0, 1.0], [0.0, 2.0]], "maxWork": oracle.WORK_LIMIT}),
    ]
    cases.extend(work_cases)
    cases.extend((
        error("invalid-missing-points", {"maxWork": 0}),
        error("invalid-extra-key", {"points": [], "maxWork": 0, "extra": 1}),
        error("invalid-point-shape", {"points": [[0.0, 0.0, 1.0]], "maxWork": 0}),
        error("invalid-boolean-coordinate", {"points": [[True, 0.0]], "maxWork": 0}),
        error("invalid-boolean-work", {"points": [], "maxWork": True}),
        error("invalid-fractional-work", {"points": [], "maxWork": 0.5}),
        error("invalid-negative-work", {"points": [], "maxWork": -1}),
        error("invalid-above-safe-work", {"points": [], "maxWork": oracle.WORK_LIMIT + 1}),
        error("invalid-before-work-budget", {"points": [[0.0, 0.0], ["not-a-number", 1.0]], "maxWork": 0}),
        error("zero-budget-nonempty", {"points": [[0.0, 0.0]], "maxWork": 0}),
    ))
    source_bindings = {
        str(DECISIONS.relative_to(ROOT)): sha(DECISIONS),
        str(NUMERIC.relative_to(ROOT)): sha(NUMERIC),
        str(POLICY.relative_to(ROOT)): sha(POLICY),
        str((ROOT / "tools/diagnostics/cp9/contract_oracle.py").relative_to(ROOT)): sha(ROOT / "tools/diagnostics/cp9/contract_oracle.py"),
        str(GEOMETRY.relative_to(ROOT)): sha(GEOMETRY),
        str(Path(__file__).relative_to(ROOT)): sha(Path(__file__)),
    }
    catalog_sha256 = None
    reviewed = False
    if catalog is not None:
        if not catalog.is_file():
            raise ValueError("catalog must name an existing regular file")
        contract = json.loads(catalog.read_text())
        if (contract.get("id"), contract.get("version"), contract.get("fixture_format")) != ("topology.delaunay-2d", "0.1.0", "delaunay-output"):
            raise ValueError("selected catalog identity/version/fixture format differs")
        reviewed = contract.get("status") == "reviewed"
        catalog_key = str(catalog.relative_to(ROOT))
        catalog_sha256 = sha(catalog)
        source_bindings[catalog_key] = catalog_sha256
    return {
        "operation": "topology.delaunay-2d",
        "version": "0.1.0",
        "fixture_format": "delaunay-output",
        "fixture_status": ("reviewed" if reviewed else "draft shared-contract vectors; native implementation validation is separate"),
        "catalog_sha256": catalog_sha256,
        "draft_decision_sha256": sha(DECISIONS),
        "source_bindings": source_bindings,
        "cases": cases,
        "cross_case_checks": [
            {"id": "duplicate-permutations-have-identical-coordinate-topology", "kind": "same-coordinate-topology", "cases": ["duplicates-negative-zero", "duplicates-reversed", "duplicates-rotated"]},
            {"id": "negative-zero-canonicalizes-in-output", "kind": "canonical-positive-zero", "case": "duplicates-negative-zero", "point_indices": [0]},
            {"id": "boundary-and-internal-insertion-work-threshold", "kind": "exact-work-threshold", "success_case": "boundary-and-internal-edge-insertions-exact-budget", "failure_case": "one-short-total", "work_used": work_thresholds["exact_work_used"]},
            {"id": "all-draft-schedule-stages-have-one-short-witnesses", "kind": "one-short-stage-witnesses", "stages": {stage: "one-short-" + stage for stage in ("canonicalize", "hull_lower", "hull_upper", "locate", "legalize")}, "thresholds": work_thresholds},
        ],
        "native_only_cases": [
            {"id": "nonfinite-and-overflowing-numeric-carriers", "description": "NaN, +/-Infinity, and numeric carriers that cannot convert to finite binary64 are INVALID_INPUT before the canonicalize budget. Strict JSON intentionally carries no nonfinite literal."},
            {"id": "passive-input-carriers-only", "description": "Recognized wrong carriers (Java arbitrary Number subclasses, JavaScript typed-array/class point pairs, Python custom mapping/list containers) are INVALID_INPUT. Active getters/proxies/custom hooks are outside passive interchange and need not be read."},
            {"id": "negative-zero", "description": "The duplicates-negative-zero success case supplies -0.0; output points and comparison bits must expose canonical +0. Native tests must cover ordinary numeric carriers and integral floating maxWork."},
            {"id": "retained-output-and-access", "description": "Ownership, detached materialization, accessor precedence, atomic destination writes, allocation failure, and the production packed-storage/no-dead-face requirement are native obligations, not claimed by these pure vectors."},
        ],
        "limitations": [
            "Vectors derive from a private Fraction work-schedule oracle, not a public or target implementation.",
            "The original .work/cp9-contract-oracle/report.json predating review1 materialized Fraction point objects before the canonicalize charge and retained dead face nodes. Review1 fixed those schedule-order and node-retention issues; review2 refreshed the decisions binding. Ignored oracle reports are optional provenance and are not required source bindings for these vectors.",
            "The current private oracle still uses object-heavy exact arithmetic and is not memory or performance evidence.",
            "The capacity ceiling is representational only. These small vectors do not exercise large allocation, native ownership/access, or target binary64 predicate implementation.",
            "Reviewed vectors bind the canonical catalog hash; draft generation without a selected catalog has a null binding and cannot establish contract acceptance.",
        ],
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="write the generated fixture; otherwise check exact regeneration")
    parser.add_argument("--output", default=str(OUT.relative_to(ROOT)), help="repository-relative JSON output path")
    parser.add_argument("--catalog", default="catalog/operations/delaunay-2d.json", help="repository-relative selected catalog file to hash-bind")
    args = parser.parse_args()
    output = repository_path(args.output, label="output")
    catalog = repository_path(args.catalog, label="catalog") if args.catalog else None
    value = build(catalog)
    text = json.dumps(value, indent=2, sort_keys=True, allow_nan=False) + "\n"
    if args.write:
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(text)
    elif not output.is_file() or output.read_text() != text:
        raise SystemExit("Fixture is missing or stale; regenerate with the same --catalog/--output and --write")
    print(json.dumps({"status": "generated" if args.write else "regeneration-verified", "cases": len(value["cases"]), "output": str(output.relative_to(ROOT)), "catalog": None if catalog is None else str(catalog.relative_to(ROOT)), "written": args.write}, sort_keys=True))


if __name__ == "__main__":
    main()
