/**
 * Search and describe projections over the generated catalog metadata. Identities,
 * schemas, defaults, bounds and support come from the generated artifacts; only ranking
 * is computed here. Every operation is searchable, and "executable here" is reported
 * separately from existence: a renderer or binding restriction is a capability reason.
 */
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import operationsApi from "../generated-api.json";
import { techniques } from "../studio";
import { fail, LIMITS, REPO_ROOT, snapshot } from "./core";

type SupportRecord = { target: string; core: string; native: string; technique: string };
type ProvenanceRecord = { candidate: string; sketch: string };
type ApiOperation = {
  id: string;
  version: string;
  role: string;
  description: string;
  input: unknown;
  query: unknown;
  queryOutput: unknown;
  output: unknown;
  errors: Record<string, string>;
  errorOrder: string[];
  behavior: Record<string, string>;
  provenance: ProvenanceRecord[];
  javascript: { exports: string[]; module: string; package: string } | null;
  support: SupportRecord[];
  sha256: string;
};
// Generated by apps/web/scripts/generate-api.mjs, which checks package binding drift.
const operations = operationsApi.operations as unknown as ApiOperation[];

const words = (text: string): string[] =>
  text
    .toLowerCase()
    .split(/[^a-z0-9]+/)
    .filter((word) => word.length > 2);

export type SearchHit = {
  kind: "workflow" | "operation";
  id: string;
  title: string;
  summary: string;
  score: number;
  executableHere: boolean;
  capabilityReason: string;
  detailHandle: string;
  route: string;
};
export type SearchResult = {
  query: string;
  target: string;
  hits: SearchHit[];
  nextCursor: number | null;
  totalMatched: number;
};

/** Ranked workflows and operations for a visual task; unbound operations stay visible. */
export function searchCatalog(
  visualTask: string,
  target: "p5js" | "processing-java" | "any",
  cursor = 0,
  limit = 12,
): SearchResult {
  if (!visualTask.trim())
    fail("request", "MALFORMED_REQUEST", "A catalog search needs a visual task description");
  const needles = words(visualTask);
  if (!needles.length) needles.push(visualTask.trim().toLowerCase());
  const capabilities = snapshot().routes,
    sourceRoute = target === "processing-java" ? "source-processing-java" : "source-p5js",
    sourceCapability = capabilities.find((entry) => entry.route === sourceRoute)!,
    workflowCapability = capabilities.find((entry) => entry.route === "workflow")!,
    recipeCapability = capabilities.find((entry) => entry.route === "recipe")!;
  const score = (haystack: string, weight: number): number => {
    const text = haystack.toLowerCase();
    let total = 0;
    for (const needle of needles) if (text.includes(needle)) total += weight;
    return total;
  };
  const hits: SearchHit[] = [];
  for (const technique of techniques) {
    const total =
      score(technique.title, 6) +
      score(technique.id, 5) +
      score(technique.description, 2) +
      score(technique.parameters.map((parameter) => parameter.key).join(" "), 1);
    if (total === 0) continue;
    hits.push({
      kind: "workflow",
      id: technique.id,
      title: technique.title,
      summary: technique.description.slice(0, 280),
      score: total,
      executableHere: target !== "processing-java" && workflowCapability.available,
      capabilityReason:
        target === "processing-java"
          ? "Studio workflows render through the browser renderer; a Processing Java request needs the source route."
          : workflowCapability.reason,
      detailHandle: `workflow:${technique.id}`,
      route: "workflow",
    });
  }
  for (const operation of operations) {
    const total =
      score(operation.id, 6) +
      score(operation.description, 2) +
      score(Object.values(operation.behavior).join(" "), 1) +
      score(operation.role, 1);
    if (total === 0) continue;
    const javascriptBinding = operation.javascript !== null,
      executableHere =
        target === "processing-java"
          ? snapshot().routes.find((entry) => entry.route === "source-processing-java")!.available
          : javascriptBinding && sourceCapability.available;
    hits.push({
      kind: "operation",
      id: operation.id,
      title: operation.id,
      summary: operation.description.slice(0, 280),
      score: total,
      executableHere,
      capabilityReason: executableHere
        ? `Callable from ${target === "processing-java" ? "the Processing Java layer runner" : `the pinned JavaScript package as ${operation.javascript?.exports[0]}`}. ${recipeCapability.reason}`
        : javascriptBinding
          ? sourceCapability.reason
          : `This operation has no JavaScript package binding; it exists and is documented, and the ${target === "processing-java" ? "Processing Java" : "native"} code route remains available.`,
      detailHandle: `operation:${operation.id}`,
      route: target === "processing-java" ? "source-processing-java" : "source-p5js",
    });
  }
  hits.sort((left, right) => right.score - left.score || left.id.localeCompare(right.id));
  const bounded = Math.min(limit, LIMITS.maxSearchResults),
    page = hits.slice(cursor, cursor + bounded);
  return {
    query: visualTask,
    target,
    hits: page,
    nextCursor: cursor + bounded < hits.length ? cursor + bounded : null,
    totalMatched: hits.length,
  };
}

export type OperationDetail = {
  id: string;
  version: string;
  role: string;
  description: string;
  schemaReferences: {
    input: string;
    query: string | null;
    queryOutput: string | null;
    output: string;
  };
  input: unknown;
  query: unknown;
  queryOutput: unknown;
  output: unknown;
  errors: Record<string, string>;
  errorOrder: string[];
  behavior: Record<string, string>;
  support: SupportRecord[];
  provenance: ProvenanceRecord[];
  javascript: { package: string; module: string; export: string; signature: string } | null;
  recipeBinding: { bound: boolean; reason: string };
  catalogSha256: string;
};
export type WorkflowDetail = {
  id: string;
  title: string;
  description: string;
  parameters: {
    key: string;
    label: string;
    description: string;
    type: string;
    min?: number;
    max?: number;
    step?: number;
    options?: string[];
  }[];
  operations: string[];
  capabilityReason: string;
};
/** Reads the audited JavaScript signature from the actual package module. */
function javascriptSignature(module: string, exported: string): string {
  const path = join(REPO_ROOT, module);
  if (!existsSync(path)) return `${exported}(...)`;
  const body = readFileSync(path, "utf8"),
    functionMatch = new RegExp(`export\\s+function\\s+${exported}\\s*\\(([^)]*)\\)`).exec(body),
    classMatch = new RegExp(`export\\s+class\\s+${exported}\\b`).exec(body);
  if (functionMatch) return `${exported}(${functionMatch[1].replace(/\s+/g, " ").trim()})`;
  if (classMatch) {
    const constructorMatch = new RegExp(
      `export\\s+class\\s+${exported}[\\s\\S]{0,400}?constructor\\s*\\(([^)]*)\\)`,
    ).exec(body);
    return `new ${exported}(${constructorMatch ? constructorMatch[1].replace(/\s+/g, " ").trim() : ""})`;
  }
  const reexport = new RegExp(`export\\s*\\{[^}]*\\b${exported}\\b`).exec(body);
  return reexport ? `${exported}(...)` : `${exported}(...)`;
}
export function describeHandles(handles: string[]): {
  operations: OperationDetail[];
  workflows: WorkflowDetail[];
  unknown: string[];
} {
  const details: OperationDetail[] = [],
    workflows: WorkflowDetail[] = [],
    missing: string[] = [],
    recipeReason = snapshot().routes.find((entry) => entry.route === "recipe")!.reason,
    boundRecipes = new Set(
      snapshot()
        .operations.filter((operation) => operation.recipeBinding)
        .map((operation) => operation.id),
    );
  for (const handle of handles.slice(0, LIMITS.maxSearchResults)) {
    const [prefix, ...rest] = handle.split(":");
    const id = rest.join(":") || prefix;
    if (prefix === "workflow" || techniques.some((technique) => technique.id === id)) {
      const technique = techniques.find((entry) => entry.id === id);
      if (!technique) {
        missing.push(handle);
        continue;
      }
      workflows.push({
        id: technique.id,
        title: technique.title,
        description: technique.description,
        parameters: technique.parameters.map((parameter) => ({
          key: parameter.key,
          label: parameter.label,
          description: parameter.description,
          type: parameter.type,
          min: parameter.min,
          max: parameter.max,
          step: parameter.step,
          options: parameter.options?.map((option) => option.value),
        })),
        operations: [],
        capabilityReason: snapshot().routes.find((entry) => entry.route === "workflow")!.reason,
      });
      continue;
    }
    const operation = operations.find((entry) => entry.id === id);
    if (!operation) {
      missing.push(handle);
      continue;
    }
    details.push({
      id: operation.id,
      version: operation.version,
      role: operation.role,
      description: operation.description,
      schemaReferences: {
        input: `catalog/operations/*.json#/input_schema (${operation.id})`,
        query: operation.query ? `catalog/operations/*.json#/query_schema (${operation.id})` : null,
        queryOutput: operation.queryOutput
          ? `catalog/operations/*.json#/query_output_schema (${operation.id})`
          : null,
        output: `catalog/operations/*.json#/output_schema (${operation.id})`,
      },
      input: operation.input,
      query: operation.query,
      queryOutput: operation.queryOutput,
      output: operation.output,
      errors: operation.errors,
      errorOrder: operation.errorOrder,
      behavior: operation.behavior,
      support: operation.support,
      provenance: operation.provenance,
      javascript: operation.javascript
        ? {
            package: operation.javascript.package,
            module: operation.javascript.module,
            export: operation.javascript.exports[0],
            signature: javascriptSignature(operation.javascript.module, operation.javascript.exports[0]),
          }
        : null,
      recipeBinding: { bound: boundRecipes.has(operation.id), reason: recipeReason },
      catalogSha256: operation.sha256,
    });
  }
  return { operations: details, workflows, unknown: missing };
}
export const operationIds = (): string[] => operations.map((operation) => operation.id);
