/**
 * Server-side harness core: repository paths, hashing, request identity, the typed
 * error taxonomy and the capability/binding snapshot. The snapshot is derived from
 * artifacts present at startup; counts and prose are never a dispatch table.
 */
import { createHash, randomUUID } from "node:crypto";
import { existsSync, mkdirSync, readFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import operationsApi from "../generated-api.json";
import gallery from "../generated-gallery.json";
import { MAX_LAYERS, techniques } from "../studio";
import {
  canonicalJson,
  catalogDigest,
  JAVA_RUNNER_PROFILE,
  MAX_TICK,
  P5_RUNNER_PROFILE,
  STUDIO_BINDING,
} from "../studio-document";

type OperationRecord = {
  id: string;
  version: string;
  role: string;
  description: string;
  javascript: { exports: string[]; module: string; package: string } | null;
  support: { target: string; core: string; native: string; technique: string }[];
  sha256: string;
};
type RecipeBindings = { status: string; operations: { id: string }[] };
// Generated by scripts/generate-api.mjs from catalog contracts; drift is checked there.
const operations = operationsApi.operations as unknown as OperationRecord[];

export const APP_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
export const REPO_ROOT = resolve(APP_ROOT, "../..");
export const WORK_ROOT = join(REPO_ROOT, ".work/harness");
export const ARTIFACT_ROOT = join(WORK_ROOT, "artifacts");
export const CANDIDATE_ROOT = join(WORK_ROOT, "candidates");
export const JOB_ROOT = join(WORK_ROOT, "jobs");
export const RUN_ROOT = join(WORK_ROOT, "runs");
export const APPLY_ROOT = join(WORK_ROOT, "applied");
export const REFERENCE_ROOT = join(WORK_ROOT, "reference");

/** Frozen quotas. A model cannot raise its own limits; every runner re-checks them. */
export const LIMITS = {
  canvasWidth: 640,
  canvasHeight: 640,
  pixelDensity: 1,
  maxLayers: MAX_LAYERS,
  maxTick: MAX_TICK,
  maxSourceBytes: 262144,
  maxSourceFiles: 6,
  maxRenderSeconds: 30,
  maxCompileSeconds: 60,
  maxRenderBytes: 8388608,
  maxHeapMegabytes: 512,
  maxRendersPerRun: 3,
  maxRepairTurns: 2,
  maxSearchResults: 24,
  maxArtifactTextBytes: 131072,
} as const;

export type HarnessStage =
  | "request"
  | "schema"
  | "type"
  | "binding"
  | "capability"
  | "scope"
  | "budget"
  | "compile"
  | "render"
  | "revision";
export type HarnessCode =
  | "MALFORMED_REQUEST"
  | "UNKNOWN_TOOL"
  | "UNKNOWN_OPERATION"
  | "UNKNOWN_HANDLE"
  | "STALE_BINDING"
  | "UNSUPPORTED_CAPABILITY"
  | "INVALID_CONTROL"
  | "MISSING_ASSET"
  | "COMPILE_FAILURE"
  | "RUNTIME_FAILURE"
  | "RESOURCE_EXHAUSTED"
  | "REVISION_CONFLICT"
  | "SCOPE_VIOLATION"
  | "LAYER_LIMIT"
  | "BUDGET_EXHAUSTED"
  | "NOT_AUTHORIZED"
  | "JOB_CANCELLED";
export type Diagnostic = {
  stage: HarnessStage;
  code: HarnessCode;
  message: string;
  location?: string;
  retryable: boolean;
};
export class HarnessError extends Error {
  readonly diagnostic: Diagnostic;
  constructor(diagnostic: Diagnostic) {
    super(diagnostic.message);
    this.name = "HarnessError";
    this.diagnostic = diagnostic;
  }
}
/** Declared as a function so `never` participates in control-flow narrowing. */
export function fail(
  stage: HarnessStage,
  code: HarnessCode,
  message: string,
  extra: { location?: string; retryable?: boolean } = {},
): never {
  throw new HarnessError({
    stage,
    code,
    message,
    location: extra.location,
    retryable: extra.retryable ?? false,
  });
}
export const sha256 = (value: string | Uint8Array): string =>
  createHash("sha256").update(value).digest("hex");
export const requestId = (): string => `req-${randomUUID()}`;
export const documentHash = (document: unknown): string => sha256(canonicalJson(document));
export const ensureDirectories = (): void => {
  for (const path of [
    ARTIFACT_ROOT,
    CANDIDATE_ROOT,
    JOB_ROOT,
    RUN_ROOT,
    APPLY_ROOT,
    REFERENCE_ROOT,
  ])
    mkdirSync(path, { recursive: true });
};

export type RouteId = "workflow" | "recipe" | "source-p5js" | "source-processing-java";
export type RouteCapability = {
  route: RouteId;
  available: boolean;
  reason: string;
  runnerProfile: string | null;
  requirements: { path: string; present: boolean }[];
};
export type CapabilitySnapshot = {
  snapshotHash: string;
  bindingVersion: string;
  catalogSha256: string;
  limits: typeof LIMITS;
  routes: RouteCapability[];
  workflows: { id: string; title: string; description: string; parameters: string[] }[];
  operations: {
    id: string;
    version: string;
    role: string;
    javascriptExport: string | null;
    recipeBinding: boolean;
    support: { target: string; core: string; native: string; technique: string }[];
  }[];
};

const requirement = (path: string) => ({ path, present: existsSync(join(REPO_ROOT, path)) });
const P5_REQUIREMENTS = [
  "apps/web/node_modules/p5/lib/p5.min.js",
  "packages/javascript/src/index.js",
  ".work/toolchains/playwright",
  "tools/harness/run_p5_layer.mjs",
];
const JAVA_REQUIREMENTS = [
  ".work/toolchains/jdk-17.0.20.1+1/bin/javac",
  ".work/toolchains/processing-4.5.6/core-4.5.6.jar",
  ".work/toolchains/processing-4.5.6/processing-4.5.6-linux-x64-portable.zip",
  "tests/native/PreprocessSketch.java",
  "tools/harness/run_java_layer.py",
];

function sandboxPresent(): boolean {
  for (const base of (process.env.PATH ?? "").split(":"))
    if (base && existsSync(join(base, "bwrap"))) return true;
  return false;
}
/** Recipe binding admission is read from the catalog, never from prose or counts. */
function recipeBindings(): RecipeBindings {
  const parsed: unknown = JSON.parse(readRepoFile("catalog/recipes/execution-bindings.json"));
  if (
    !parsed ||
    typeof parsed !== "object" ||
    !("status" in parsed) ||
    typeof parsed.status !== "string" ||
    !("operations" in parsed) ||
    !Array.isArray(parsed.operations)
  )
    throw new Error("catalog/recipes/execution-bindings.json is not a bindings record");
  const status = parsed.status,
    entries = parsed.operations.map((entry: unknown) => {
      if (!entry || typeof entry !== "object" || !("id" in entry) || typeof entry.id !== "string")
        throw new Error("catalog/recipes/execution-bindings.json has an unusable operation entry");
      return { id: entry.id };
    });
  return { status, operations: entries };
}
function routes(bindings: RecipeBindings): RouteCapability[] {
  const p5 = P5_REQUIREMENTS.map(requirement),
    java = JAVA_REQUIREMENTS.map(requirement),
    sandbox = { path: "bwrap", present: sandboxPresent() },
    p5Ready = p5.every((item) => item.present),
    javaReady = java.every((item) => item.present) && sandbox.present;
  return [
    {
      route: "workflow",
      available: true,
      reason: `${techniques.length} registered studio workflows render through the existing browser renderer.`,
      runnerProfile: STUDIO_BINDING,
      requirements: [requirement("apps/web/lib/render-studio.ts")],
    },
    {
      route: "source-p5js",
      available: p5Ready,
      reason: p5Ready
        ? "Generated p5.js source runs in a disposable browser process on an isolated origin."
        : `Missing p5 runner inputs: ${p5
            .filter((item) => !item.present)
            .map((item) => item.path)
            .join(", ")}`,
      runnerProfile: P5_RUNNER_PROFILE,
      requirements: p5,
    },
    {
      route: "source-processing-java",
      available: javaReady,
      reason: javaReady
        ? "Generated Processing Java compiles and renders offscreen inside a network-isolated OS sandbox."
        : `Missing Java runner inputs: ${[...java, sandbox]
            .filter((item) => !item.present)
            .map((item) => item.path)
            .join(", ")}`,
      runnerProfile: JAVA_RUNNER_PROFILE,
      requirements: [...java, sandbox],
    },
    {
      route: "recipe",
      available: false,
      reason: `Recipe execution bindings remain ${bindings.status} in catalog/recipes/execution-bindings.json (${bindings.operations.length} proposed operations, no admitted executor); use the source route for these operations.`,
      runnerProfile: null,
      requirements: [requirement("catalog/recipes/execution-bindings.json")],
    },
  ];
}

let cached: CapabilitySnapshot | null = null;
/** Derived from artifacts on disk at first call; restart the service after changing them. */
export function snapshot(): CapabilitySnapshot {
  if (cached) return cached;
  const bindings = recipeBindings(),
    boundRecipes = new Set(bindings.operations.map((entry) => entry.id));
  const body = {
    bindingVersion: STUDIO_BINDING,
    catalogSha256: catalogDigest(),
    limits: LIMITS,
    routes: routes(bindings),
    workflows: techniques.map((technique) => ({
      id: technique.id,
      title: technique.title,
      description: technique.description,
      parameters: technique.parameters.map((parameter) => parameter.key),
    })),
    operations: operations.map((operation) => ({
      id: operation.id,
      version: operation.version,
      role: operation.role,
      javascriptExport: operation.javascript?.exports?.[0] ?? null,
      recipeBinding: boundRecipes.has(operation.id),
      support: operation.support,
    })),
  };
  cached = { snapshotHash: sha256(canonicalJson(body)), ...body };
  return cached;
}
export const snapshotHash = (): string => snapshot().snapshotHash;
export function requireRoute(route: RouteId): RouteCapability {
  const found = snapshot().routes.find((entry) => entry.route === route);
  if (!found)
    fail("capability", "UNSUPPORTED_CAPABILITY", `Unknown execution route: ${route}`);
  return found!;
}
/** Reads the studio binding digest recorded with the generated gallery. */
export const galleryBinding = (): { version: string; catalogSha256: string } => ({
  version: gallery.studioBinding.version,
  catalogSha256: gallery.studioBinding.catalogSha256,
});
export const readRepoFile = (relative: string): string =>
  readFileSync(join(REPO_ROOT, relative), "utf8");
