/** Bounded ProfileMarks p5 WEBGL probe. Run only under tools/with_native_render_lock.py. */
import fs from "node:fs/promises";
import path from "node:path";
import http from "node:http";
import { fileURLToPath } from "node:url";
import { createHash } from "node:crypto";
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), ".."), runtime = path.join(root, ".work/environments/p5js"), args = process.argv.slice(2);
if (args.length !== 2 || args[0] !== "--output") throw new Error("Usage: --output FRESH_DIRECTORY");
const output = path.resolve(args[1]); if (!output.startsWith(path.join(root, ".work") + path.sep)) throw new Error("Output must stay under .work"); await fs.mkdir(path.dirname(output), { recursive: true }); await fs.mkdir(output);
const names = ["tools/run_p5_profile_marks.mjs", "tests/native/profile-marks-browser.mjs", "packages/javascript/examples/profile-marks/index.html", "packages/javascript/examples/profile-marks/sketch.js", "packages/javascript/examples/profile-marks/profile-marks.js", "packages/javascript/examples/profile-marks/README.md", "packages/javascript/src/radial-profile.js", "packages/javascript/src/cyclic-palette.js", "catalog/operations/radial-profile-surface.json", "fixtures/operations/radial-profile-surface.json", "design/capabilities/profile-marks-port-boundary.md", "design/capabilities/profile-marks-p5-acceptance.md", ".work/environments/p5js/package-lock.json", ".work/environments/p5js/node_modules/p5/lib/p5.min.js", ".work/environments/p5js/node_modules/playwright/package.json"];
const digest = bytes => createHash("sha256").update(bytes).digest("hex"), hashes = async () => Object.fromEntries(await Promise.all(names.map(async name => [name, digest(await fs.readFile(path.join(root, name)))])));
const report = { status: "failed", scope: "ProfileMarks p5.js WEBGL workflow only; no release or support acceptance", input_sha256_before: await hashes(), states: [], errors: [] };
await fs.writeFile(path.join(output, "attempt.json"), JSON.stringify(report, null, 2));
const allowed = new Set(names.filter(name => name.startsWith("packages/") || name.startsWith("tests/")).map(name => "/" + name));
const server = http.createServer(async (request, response) => { try { const name = new URL(request.url, "http://localhost").pathname, file = name === "/p5.js" ? path.join(runtime, "node_modules/p5/lib/p5.min.js") : allowed.has(name) ? path.join(root, name.slice(1)) : null; if (!file) { response.writeHead(404); response.end(); return; } response.setHeader("Content-Type", file.endsWith(".html") ? "text/html" : "text/javascript"); response.end(await fs.readFile(file)); } catch { response.writeHead(500); response.end(); } });
let browser; const timer = setTimeout(() => { console.error("ProfileMarks browser deadline exceeded"); process.exit(1); }, 180000);
try {
  process.env.PLAYWRIGHT_BROWSERS_PATH = path.join(root, ".work/toolchains/playwright"); const { chromium } = await import(path.join(runtime, "node_modules/playwright/index.mjs"));
  await new Promise((resolve, reject) => { server.once("error", reject); server.listen(0, "127.0.0.1", resolve); }); const origin = `http://127.0.0.1:${server.address().port}`;
  browser = await chromium.launch({ timeout: 30000 }); const page = await (await browser.newContext({ viewport: { width: 800, height: 1000 }, deviceScaleFactor: 1 })).newPage(); page.setDefaultTimeout(15000); page.on("pageerror", error => report.errors.push(String(error))); page.on("console", message => { if (message.type() === "error") report.errors.push(message.text()); });
  await page.goto(origin + "/packages/javascript/examples/profile-marks/index.html"); await page.waitForFunction(() => document.querySelector("#art")?.dataset.revision === "1");
  async function state(id, expected) { await page.waitForFunction(revision => document.querySelector("#art")?.dataset.revision === String(revision), expected.revision); const observation = await page.evaluate(async value => (await import("/tests/native/profile-marks-browser.mjs")).observe(value), expected); const png = Buffer.from((await page.evaluate(() => document.querySelector("#art canvas").toDataURL("image/png"))).split(",")[1], "base64"); await page.locator("#art canvas").screenshot({ path: path.join(output, id + "-display.png") }); await fs.writeFile(path.join(output, id + ".png"), png); report.states.push({ id, ...observation, png_sha256: digest(png), display_png: id + "-display.png" }); return png; }
  const base = { profile: 0, slices: 32, capStart: true, capEnd: true, alternate: false, trio: false };
  const sequence = [["baseline", null, 1088, base, false, true], ["waist", "p", 1088, { ...base, profile: 1 }, true], ["pointed", "p", 1024, { ...base, profile: 2 }, true], ["coarse", "d", 256, { ...base, profile: 2, slices: 8 }, false], ["cylinder", "p", 272, { ...base, slices: 8 }, true], ["start-open", "b", 264, { ...base, slices: 8, capStart: false }, false], ["both-open", "t", 256, { ...base, slices: 8, capStart: false, capEnd: false }, false], ["palette", "c", 256, { ...base, slices: 8, capStart: false, capEnd: false, alternate: true }, true], ["trio", "x", 760, { ...base, slices: 8, capStart: false, capEnd: false, alternate: true, trio: true }, true], ["reset", "0", 1088, base, false, true]];
  let baseline, trio; for (let i = 0; i < sequence.length; i += 1) { const [id, key, faces, settings, retained, baselineState] = sequence[i]; if (key) await page.locator(`button[data-action="${key}"]`).click(); const image = await state(id, { revision: i + 1, faces, settings, retained, baseline: baselineState }); if (!baseline) baseline = image; if (id === "trio") { trio = image; const event = page.waitForEvent("download"); await page.locator('button[data-action="s"]').click(); const download = await event; await download.saveAs(path.join(output, "saved-trio.png")); if (!(await fs.readFile(path.join(output, "saved-trio.png"))).equals(trio)) throw new Error("cached trio save differs"); await page.waitForTimeout(100); report.trio_save = await page.evaluate(async expected => (await import("/tests/native/profile-marks-browser.mjs")).observe(expected), { revision: i + 1, faces, settings, retained: true }); } if (baselineState && !baseline.equals(image)) throw new Error("baseline image changed"); }
  const downloadEvent = page.waitForEvent("download"); await page.locator('button[data-action="s"]').click(); const download = await downloadEvent; await download.saveAs(path.join(output, "saved.png")); const saved = await fs.readFile(path.join(output, "saved.png")); if (!saved.equals(baseline)) throw new Error("cached saved image differs from acknowledged reset"); await page.waitForTimeout(100); report.reset_save = await page.evaluate(async expected => (await import("/tests/native/profile-marks-browser.mjs")).observe(expected), { revision: 10, faces: 1088, settings: base, retained: true, baseline: true }); if (report.errors.length) throw new Error("browser errors"); report.input_sha256_after = await hashes(); if (JSON.stringify(report.input_sha256_before) !== JSON.stringify(report.input_sha256_after)) throw new Error("inputs changed during run"); report.status = "passed";
} catch (error) { report.failure = String(error.stack ?? error); }
finally { try { if (browser) await browser.close(); } catch {} server.closeAllConnections(); await new Promise(resolve => server.close(resolve)); clearTimeout(timer); await fs.writeFile(path.join(output, "result.json"), JSON.stringify(report, null, 2) + "\n"); }
console.log(JSON.stringify({ status: report.status, output, failure: report.failure })); if (report.status !== "passed") process.exitCode = 1;
