import { componentSeed } from "./core.js";
import { createRecording } from "./recording.js";
import type { Recording } from "./recording.js";

/**
 * Bundled sample recordings: deterministic stand-ins for a host's captured strokes, so the
 * Gesture Scores study works without any host-owned asset. Each is generated by a fixed
 * closed-form curve `c(u)`, a timing profile (how fast the hand moves along it, including exact
 * rests), a nominal event rate with deterministic timestamp jitter, and an optional pressure
 * function; the seed selects the take (`take` below). Nothing here is a captured performance.
 *
 * Every recording starts at t = 0, ends exactly at its duration, and has strictly increasing
 * timestamps (jitter is below 45% of a period). They differ in rate, regularity and pressure:
 *
 * | id | duration | nominal rate | pressure | character |
 * |---|---|---|---|---|
 * | `sweep` | 2.6 s | 90 Hz | yes, swelling | one broad swooping stroke, fast in the middle |
 * | `spiral` | 3.4 s | 60 Hz | yes, with presses | outward spiral with two exact rests |
 * | `loops` | 3.2 s | 120 Hz | yes, per loop | chain of cursive loops |
 * | `scribble` | 4.2 s | 30 Hz | none | dense back-and-forth scribble |
 * | `wander` | 3.6 s | 75 Hz | yes | smooth random hand, different per seed |
 */
export const bundledRecordingIds = ["sweep", "spiral", "loops", "scribble", "wander"] as const;
export type BundledRecordingId = (typeof bundledRecordingIds)[number];

/** What each bundled recording is, for selectors and cheap validation (durations are exact). */
export const bundledRecordingInfo: Readonly<Record<BundledRecordingId, { title: string; duration: number; rate: number; pressure: boolean }>> = Object.freeze({
  sweep: { title: "Broad sweep · 90 Hz", duration: 2600, rate: 90, pressure: true },
  spiral: { title: "Spiral with rests · 60 Hz", duration: 3400, rate: 60, pressure: true },
  loops: { title: "Cursive loops · 120 Hz", duration: 3200, rate: 120, pressure: true },
  scribble: { title: "Scribble, no pressure · 30 Hz", duration: 4200, rate: 30, pressure: false },
  wander: { title: "Wandering hand · 75 Hz, per seed", duration: 3600, rate: 75, pressure: true },
});

interface Spec {
  id: string;
  duration: number;
  rate: number;
  /** Fraction of a period by which each interior event time is displaced (below 0.45). */
  jitter: number;
  seed: number;
  curve: (u: number) => readonly [number, number];
  /** Non-negative speed along the curve at normalized time; zero is an exact rest. */
  pace: (tau: number) => number;
  pressure: ((u: number, tau: number) => number) | null;
}

const TABLE = 4096;
const U32 = 0x1_0000_0000;

function generate(spec: Spec): Recording {
  // Curve position u(tau): the normalized integral of the pace, tabulated once.
  const cumulative = new Float64Array(TABLE + 1);
  for (let i = 1; i <= TABLE; i++) cumulative[i] = cumulative[i - 1] + (spec.pace((i - 1) / TABLE) + spec.pace(i / TABLE)) / 2;
  const total = cumulative[TABLE];
  const u = (tau: number): number => {
    const position = tau * TABLE, i = Math.min(TABLE - 1, Math.floor(position));
    return (cumulative[i] + (cumulative[i + 1] - cumulative[i]) * (position - i)) / total;
  };
  const period = 1000 / spec.rate, times = [0];
  for (let i = 1; i * period < spec.duration - 0.3 * period; i++)
    times.push(i * period + (componentSeed(spec.seed, `t:${i}`, "jitter") / U32 * 2 - 1) * spec.jitter * period);
  times.push(spec.duration);
  const x: number[] = [], y: number[] = [], pressure: number[] = [];
  for (const time of times) {
    const tau = time / spec.duration, position = u(tau), [px, py] = spec.curve(position);
    x.push(px); y.push(py);
    if (spec.pressure) pressure.push(Math.min(1, Math.max(0, spec.pressure(position, tau))));
  }
  return createRecording({ id: spec.id, t: times, x, y, pressure: spec.pressure ? pressure : null });
}

const TAU = Math.PI * 2;
const bump = (tau: number, center: number, width: number) => Math.exp(-(((tau - center) / width) ** 2));
const unit = (seed: number, id: string, purpose: string) => componentSeed(seed, id, purpose) / U32;

function wanderSpec(seed: number): Spec {
  const harmonic = (axis: string, index: number) => ({
    frequency: 0.45 + 2.9 * unit(seed, `${axis}:${index}`, "frequency"),
    phase: TAU * unit(seed, `${axis}:${index}`, "phase"),
    amplitude: 1 / (1 + 1.3 * index),
  });
  const xs = [0, 1, 2, 3].map((index) => harmonic("x", index)), ys = [0, 1, 2, 3].map((index) => harmonic("y", index));
  const raw = (u: number): [number, number] => [
    xs.reduce((sum, h) => sum + h.amplitude * Math.sin(TAU * h.frequency * u + h.phase), 0),
    ys.reduce((sum, h) => sum + h.amplitude * Math.sin(TAU * h.frequency * u + h.phase), 0),
  ];
  // Fit the fixed-frequency curve to a fixed box so every seed fills the canvas comparably.
  let minX = Infinity, maxX = -Infinity, minY = Infinity, maxY = -Infinity;
  for (let i = 0; i <= 512; i++) {
    const [px, py] = raw(i / 512);
    minX = Math.min(minX, px); maxX = Math.max(maxX, px); minY = Math.min(minY, py); maxY = Math.max(maxY, py);
  }
  const scale = Math.min(460 / Math.max(maxX - minX, 1e-6), 400 / Math.max(maxY - minY, 1e-6));
  const pf = [0, 1, 2].map((index) => ({ frequency: 0.6 + 2.2 * unit(seed, `p:${index}`, "frequency"), phase: TAU * unit(seed, `p:${index}`, "phase") }));
  return {
    id: `wander:${seed}`, duration: 3600, rate: 75, jitter: 0.3, seed,
    curve: (u) => { const [px, py] = raw(u); return [320 + (px - (minX + maxX) / 2) * scale, 320 + (py - (minY + maxY) / 2) * scale]; },
    pace: (tau) => 0.45 + 0.55 * Math.sin(Math.PI * tau) ** 0.7,
    pressure: (u) => 0.5 + 0.25 * Math.sin(TAU * pf[0].frequency * u + pf[0].phase) + 0.2 * Math.sin(TAU * pf[1].frequency * u + pf[1].phase),
  };
}

function specFor(id: BundledRecordingId, seed: number): Spec {
  switch (id) {
    case "sweep":
      return {
        id, duration: 2600, rate: 90, jitter: 0.3, seed: 0,
        curve: (u) => {
          const t = u * TAU * 0.92 - 0.35;
          return [320 + 245 * Math.sin(t) + 40 * Math.sin(2 * t), 330 - 190 * Math.cos(t * 0.9 + 0.2) * (0.9 + 0.3 * Math.sin(3 * t)) + 90 * Math.sin(u * 3.2)];
        },
        pace: (tau) => 0.22 + Math.sin(Math.PI * tau) ** 2,
        pressure: (u, tau) => 0.1 + 0.9 * Math.sin(Math.PI * tau ** 0.85) ** 1.1 + 0.05 * Math.sin(TAU * 5 * tau),
      };
    case "spiral":
      return {
        id, duration: 3400, rate: 60, jitter: 0.25, seed: 0,
        curve: (u) => {
          const theta = TAU * 2.75 * u, r = 14 + 250 * u ** 0.92;
          return [320 + r * Math.cos(theta), 320 + r * 0.86 * Math.sin(theta)];
        },
        // Two exact rests, at 30-36% and 66-71% of the time.
        pace: (tau) => (tau > 0.3 && tau < 0.36) || (tau > 0.66 && tau < 0.71) ? 0 : 0.4 + 0.6 * Math.sin(Math.PI * tau) ** 1.5,
        pressure: (u, tau) => 0.3 + 0.4 * u + 0.3 * bump(tau, 0.33, 0.03) + 0.3 * bump(tau, 0.685, 0.03),
      };
    case "loops":
      return {
        id, duration: 3200, rate: 120, jitter: 0.4, seed: 0,
        curve: (u) => {
          const theta = TAU * 5 * u;
          return [64 + 16.4 * theta - 44 * Math.sin(theta), 320 - 44 * Math.cos(theta) + 34 * Math.sin(TAU * 1.2 * u)];
        },
        pace: (tau) => 0.6 + 0.4 * Math.sin(TAU * 3 * tau),
        pressure: (u) => 0.55 + 0.4 * Math.sin(TAU * 5 * u + 1.1),
      };
    case "scribble":
      return {
        id, duration: 4200, rate: 30, jitter: 0.45, seed: 0,
        curve: (u) => [
          320 + 236 * Math.sin(TAU * 4.3 * u + 0.6) * (0.65 + 0.35 * Math.sin(TAU * 0.9 * u)),
          320 + 200 * Math.sin(TAU * 5.9 * u + 1) * (0.7 + 0.3 * Math.cos(TAU * 1.3 * u)),
        ],
        pace: (tau) => 0.55 + 0.45 * Math.sin(TAU * 2 * tau) ** 2,
        pressure: null,
      };
    case "wander":
      return wanderSpec(seed);
  }
}

/**
 * The seed is the take: every fixed recording is performed a little differently for each seed, by a
 * slow tempo modulation (speed times `1 + 0.3 sin`, so rests stay exact) and a smooth spatial drift
 * of up to 22 canvas units per axis. The wandering hand is different from scratch.
 */
function take(spec: Spec, seed: number): Spec {
  const draw = (purpose: string) => unit(seed, spec.id, purpose);
  const tempo = { f: 1 + 2 * draw("tempoF"), phase: TAU * draw("tempoP") };
  const drift = [0, 1].map((axis) => ({ f: 0.7 + 1.8 * draw(`driftF${axis}`), phase: TAU * draw(`driftP${axis}`) }));
  return { ...spec, id: `${spec.id}:${seed}`, seed,
    curve: (u) => { const [x, y] = spec.curve(u); return [x + 22 * Math.sin(TAU * drift[0].f * u + drift[0].phase), y + 22 * Math.sin(TAU * drift[1].f * u + drift[1].phase)]; },
    pace: (tau) => spec.pace(tau) * (1 + 0.3 * Math.sin(TAU * tempo.f * tau + tempo.phase)) };
}

const cache = new Map<string, Recording>();
/** A bundled recording; its seed selects the take (see `take`). Ids are `<name>:<seed>`. */
export function bundledRecording(id: BundledRecordingId, seed: number): Recording {
  if (!(bundledRecordingIds as readonly string[]).includes(id)) throw new Error(`Unknown bundled recording: ${id}`);
  if (!Number.isSafeInteger(seed) || seed < 0 || seed > 0xffffffff) throw new Error("Recording seed must be a uint32 integer");
  const key = `${id}:${seed}`;
  const hit = cache.get(key);
  if (hit) return hit;
  const spec = specFor(id, seed);
  const recording = generate(id === "wander" ? spec : take(spec, seed));
  cache.set(key, recording);
  if (cache.size > 12) cache.delete(cache.keys().next().value!);
  return recording;
}
